// Arc POC 0.3.4 — experience integrity pass.
function ensure034(){
  S.profile=S.profile||{}; S.logs=S.logs||{};
  S.history=S.history||{workouts:[],nutrition:[],body:[]};
  S.history.workouts=S.history.workouts||[]; S.history.nutrition=S.history.nutrition||[]; S.history.body=S.history.body||[];
  S.profile.activities=S.profile.activities||['Strength training','Walking'];
  S.profile.equipment=S.profile.equipment||['Dumbbells','Bodyweight'];
  S.logs.workouts=S.history.workouts.length||S.logs.workouts||0;
  save();
}
ensure034();

const dayKey=()=>new Date().toISOString().slice(0,10);
const todayNutrition=()=>S.history.nutrition.filter(x=>x.date===dayKey());
const sumNutrition=()=>todayNutrition().reduce((a,x)=>({cal:a.cal+(+x.calories||0),protein:a.protein+(+x.protein||0)}),{cal:0,protein:0});
function syncNutrition(){const t=sumNutrition();S.logs.cal=t.cal;S.logs.protein=t.protein;save();return t}
function statusData(){
  const streams={Training:S.history.workouts.length>0,Body:S.history.body.length>0,Nutrition:S.history.nutrition.length>0,Activity:(S.logs.steps||0)>0};
  const active=Object.values(streams).filter(Boolean).length;
  return {streams,active,label:active<2?'Getting started':active<4?'Building context':'Context established'};
}
function initialHypothesis(){
  const p=S.profile||{}; let fit=`A ${p.days||3}-day, ${p.duration||30}-minute schedule may fit the routine you described.`;
  if(String(p.life).includes('Very physical')) fit+=` Because your days are already physically demanding, Arc will watch recovery and completion before adding more.`;
  else if(String(p.life).includes('Mostly sitting')) fit+=` Arc will also watch whether regular movement helps make the plan easier to sustain.`;
  else fit+=` Arc will watch whether you can repeat it consistently before recommending more.`;
  return fit;
}

capture=function(){
  const p=S.profile;
  if($('#name'))p.name=$('#name').value.trim();
  if(document.querySelectorAll('.goal').length){p.goals=[...document.querySelectorAll('.goal:checked')].map(x=>x.value);p.primary=p.goals[0]||'Improve overall health'}
  if($('#why'))p.why=$('#why').value.trim(); if($('#weight'))p.weight=$('#weight').value; if($('#waist'))p.waist=$('#waist').value;
  const life=$('input[name=life]:checked'); if(life)p.life=life.value; if($('#sleep'))p.sleep=$('#sleep').value;
  if($('#location'))p.location=$('#location').value; if($('#experience'))p.experience=$('#experience').value;
  const nut=$('input[name=nut]:checked'); if(nut)p.nutrition=nut.value;
  if(document.querySelectorAll('.activity-pref').length)p.activities=[...document.querySelectorAll('.activity-pref:checked')].map(x=>x.value);
  if(document.querySelectorAll('.equipment-pref').length)p.equipment=[...document.querySelectorAll('.equipment-pref:checked')].map(x=>x.value);
  save();
};

plan=function(){
  const p=S.profile||{}, goal=p.primary||p.goals?.[0]||'Improve overall health', acts=p.activities||[], eq=p.equipment||[];
  let focus=p.days<=2?'Make consistency easy':p.days>=5?'Balance training and recovery':'Build consistency';
  const strength=acts.includes('Strength training')||goal.includes('muscle')||goal.includes('strong');
  const endurance=acts.some(x=>['Walking','Running','Cycling','HIIT','Sports'].includes(x))||goal.includes('endurance');
  let split=[];
  if(strength){
    split=p.days==1?['Full Body Foundation']:p.days==2?['Full Body A','Full Body B']:p.days==3?['Full Body Strength','Lower Body + Core','Upper Body + Mobility']:['Lower Body Strength','Upper Body Strength','Full Body Strength','Mobility + Core','Conditioning'].slice(0,p.days);
  } else if(endurance){
    split=['Foundation Cardio','Strength + Core','Easy Endurance','Mobility + Recovery','Long Easy Session'].slice(0,p.days);
  } else split=['Full Body Foundation','Mobility + Core','Low-Impact Conditioning','Full Body Strength','Recovery Session'].slice(0,p.days);
  const equipment=eq.length?eq.join(', '):'bodyweight';
  return {focus,split,equipment};
};

function exerciseSet(workoutName){
  const eq=S.profile.equipment||[]; const db=eq.includes('Dumbbells'); const gym=eq.includes('Gym machines'); const band=eq.includes('Resistance bands');
  if(workoutName.includes('Lower')) return [db?'Goblet Squat':'Bodyweight Squat',db?'Romanian Deadlift':band?'Band Hip Hinge':'Glute Bridge','Reverse Lunge','Calf Raise','Dead Bug'];
  if(workoutName.includes('Upper')) return [db?'Dumbbell Floor Press':'Incline Push-Up',db?'One-Arm Dumbbell Row':band?'Band Row':'Supported Row',db?'Shoulder Press':'Pike Press','Biceps Curl','Side Plank'];
  if(workoutName.includes('Cardio')||workoutName.includes('Endurance')||workoutName.includes('Conditioning')) return ['Warm-Up Walk','Steady Cardio','Tempo Interval','Easy Recovery','Cooldown Walk'];
  if(workoutName.includes('Mobility')||workoutName.includes('Recovery')) return ['Cat-Cow','World’s Greatest Stretch','Glute Bridge','Dead Bug','Breathing Reset'];
  return [db?'Goblet Squat':'Bodyweight Squat',db?'Romanian Deadlift':'Glute Bridge',db?'Supported Row':band?'Band Row':'Incline Push-Up',db?'Floor Press':'Incline Push-Up','Dead Bug'];
}

onboard=function(){
  const n=S.on,p=S.profile;
  const chapter=[['Define success','What would you like to change?','Choose what matters. Your first selection becomes the primary goal Arc watches most closely.'],['Your why','Why does this matter to you?','Optional, but useful context for keeping your plan connected to real life.'],['Starting point','Give Arc a baseline.','These numbers are reference points—not grades. You can skip what you don’t want to track.'],['Real life','What does a normal day look like?','Arc should fit the life you actually have, not the week you wish you had.'],['Training','Build around your reality.','Tell Arc what you enjoy, what you have, and what you can realistically repeat.'],['Nutrition','Track on your terms.','Choose the level of detail that feels sustainable. More logging is not automatically better.']][n-1];
  let content='';
  if(n===1) content=`<div class="field-block"><label>Your name</label><input id="name" class="input" placeholder="First name" value="${esc(p.name||'Kimberly')}"></div><div class="goal-grid">${goals.map((g,i)=>`<label class="goal-card"><input class="goal" type="checkbox" value="${g}" ${p.goals.includes(g)?'checked':''}><span class="goal-number">0${i+1}</span><b>${g}</b><small>${['Change body composition','Support lean mass','Build measurable capability','Improve work capacity','Feel more at home in your body','Support daily capacity','Build repeatable habits','Create a stronger foundation','Connect the dots'][i]}</small></label>`).join('')}</div>`;
  if(n===2) content=`<div class="why-card"><span class="eyebrow">Context, not pressure</span><textarea id="why" class="input why-input" rows="7" placeholder="I want to feel stronger, more confident, and have more energy...">${esc(p.why||'')}</textarea><div class="why-example"><span>Example</span><p>“I want to feel comfortable in my clothes again and have more energy with my family.”</p></div></div>`;
  if(n===3) content=`<div class="baseline-entry-grid"><div class="metric-entry"><span>01</span><label>Weight</label><div><input id="weight" class="input" type="number" step="0.1" value="${p.weight||''}" placeholder="—"><b>lb</b></div><small>Optional</small></div><div class="metric-entry"><span>02</span><label>Waist</label><div><input id="waist" class="input" type="number" step="0.1" value="${p.waist||''}" placeholder="—"><b>in</b></div><small>Optional</small></div></div><div class="measurement-note"><span>✦</span><div><b>The trend is the story.</b><p>One number can fluctuate. Arc becomes more useful when repeated measurements are viewed alongside your behaviors.</p></div></div>`;
  if(n===4) content=`<div class="choice-grid-v033">${['Mostly sitting','A mix of sitting and moving','Mostly moving','Very physical'].map((x,i)=>`<label class="select-card"><input name="life" value="${x}" type="radio" ${p.life===x?'checked':''}><span class="select-icon">${['▰','◫','↗','◆'][i]}</span><b>${x}</b></label>`).join('')}</div><div class="field-block sleep-block"><label>Typical sleep</label><select id="sleep" class="input">${['5 or less','6','7','8','9+'].map(x=>`<option ${p.sleep===x?'selected':''}>${x}</option>`).join('')}</select><small>hours / night</small></div>`;
  if(n===5){const activities=['Strength training','Walking','Running','Cycling','Yoga','Pilates','HIIT','Sports'];const equipment=['Bodyweight','Dumbbells','Resistance bands','Gym machines'];content=`<div class="training-two-col"><div><label class="field-label">What do you enjoy doing?</label><div class="preference-grid">${activities.map(x=>`<label><input class="activity-pref" type="checkbox" value="${x}" ${p.activities?.includes(x)?'checked':''}><span>${x}</span></label>`).join('')}</div><label class="field-label">What equipment do you have?</label><div class="preference-grid">${equipment.map(x=>`<label><input class="equipment-pref" type="checkbox" value="${x}" ${p.equipment?.includes(x)?'checked':''}><span>${x}</span></label>`).join('')}</div></div><div><label class="field-label">Where do you train?</label><select id="location" class="input">${['Home','Gym','Home + Gym'].map(x=>`<option ${p.location===x?'selected':''}>${x}</option>`).join('')}</select><label class="field-label">Experience</label><select id="experience" class="input">${['New — teach me everything','Know the basics','Experienced — give me control'].map(x=>`<option ${p.experience===x?'selected':''}>${x}</option>`).join('')}</select><label class="field-label">Realistically, how many days?</label><div class="number-pills">${[1,2,3,4,5].map(x=>`<button type="button" data-days="${x}" class="${p.days===x?'active':''}">${x}</button>`).join('')}</div><label class="field-label duration-label">Time per workout</label><div class="number-pills duration-pills">${[20,30,45,60].map(x=>`<button type="button" data-duration="${x}" class="${p.duration===x?'active':''}">${x}<small>min</small></button>`).join('')}</div></div></div>`}
  if(n===6) content=`<div class="nutrition-mode-grid">${['Simple — better choices, less logging','Guided — calories + protein','Detailed — calories + macros','Not right now'].map((x,i)=>`<label class="nutrition-mode"><input name="nut" value="${x}" type="radio" ${p.nutrition===x?'checked':''}><div><span>${['LIGHT TOUCH','RECOMMENDED','FULL DETAIL','SKIP FOR NOW'][i]}</span><b>${x.split(' — ')[0]}</b><p>${['Focus on consistency without numbers.','Enough structure to create useful context.','Track calories, protein and macros.','Arc can still learn from training and body data.'][i]}</p></div></label>`).join('')}</div><div class="measurement-note"><span>✦</span><div><b>No fake precision.</b><p>Arc will not invent calorie or protein targets from incomplete information. You can set or refine guides later.</p></div></div>`;
  shell(`<div class="onboarding-shell"><div class="arc-brandbar intro-brand"><div class="arc-wordmark"><span class="arc-mini-mark"></span><b>ARC</b><small>BUILD YOUR BASELINE</small></div><span class="step-count">${String(n).padStart(2,'0')} / 06</span></div><div class="onboard-progress"><i style="width:${n/6*100}%"></i></div><div class="onboard-layout"><aside class="chapter-rail"><span class="eyebrow">Chapter ${String(n).padStart(2,'0')}</span><h1>${chapter[1]}</h1><p>${chapter[2]}</p><div class="chapter-list">${['Success','Why','Body','Life','Training','Nutrition'].map((x,i)=>`<div class="${i===n-1?'active':''} ${i<n-1?'done':''}"><i>${i<n-1?'✓':String(i+1).padStart(2,'0')}</i><span>${x}</span></div>`).join('')}</div></aside><section class="onboard-content"><span class="eyebrow">${chapter[0]}</span>${content}<div class="onboard-actions"><button class="btn secondary back-btn" data-back>← Back</button><button class="btn next-btn" data-next>${n===6?'Build My Baseline →':'Continue →'}</button></div></section></div></div>`)
};

baseline=function(){
  const p=S.profile,q=plan(),primary=p.primary||p.goals?.[0]||'Improve overall health',nutrition=String(p.nutrition||'Guided').split(' — ')[0];
  shell(`<div class="onboarding-shell reveal-shell"><div class="arc-brandbar intro-brand"><div class="arc-wordmark"><span class="arc-mini-mark"></span><b>ARC</b><small>YOUR STARTING POINT</small></div><span class="tiny muted">BASELINE READY</span></div><div class="reveal-head"><span class="eyebrow">Your baseline is ready</span><h1>${esc(p.name||'Kimberly')}, this is where your Arc begins.</h1><p>Not a verdict. A starting hypothesis Arc can test against what your body actually does.</p></div><div class="reveal-grid"><div class="reveal-primary"><div class="baseline-visual"><div class="reveal-orbit r1"></div><div class="reveal-orbit r2"></div><div class="baseline-center"><span>✦</span><b>START</b><small>YOUR ARC</small></div><div class="baseline-tag bt1"><span>GOAL</span><b>${esc(primary)}</b></div><div class="baseline-tag bt2"><span>TRAIN</span><b>${p.days} × ${p.duration} min</b></div><div class="baseline-tag bt3"><span>PREFER</span><b>${esc((p.activities||[]).slice(0,2).join(' + ')||'Flexible')}</b></div><div class="baseline-tag bt4"><span>BODY</span><b>${p.weight?p.weight+' lb':'Optional'}${p.waist?' · '+p.waist+' in waist':''}</b></div></div>${p.why?`<div class="why-reveal"><span class="eyebrow">Why this matters</span><h3>“${esc(p.why)}”</h3></div>`:''}</div><div class="reveal-detail"><div class="card first-focus"><span class="eyebrow">Arc’s first hypothesis</span><h2>${q.focus}.</h2><p>${esc(initialHypothesis())}</p><div class="focus-lines"><div><i>01</i><span><b>${p.days} planned sessions</b><small>${p.duration} minutes · ${esc(p.location)} · ${esc(q.equipment)}</small></span></div><div><i>02</i><span><b>${esc(nutrition)} nutrition mode</b><small>No calorie target is assumed from incomplete data.</small></span></div><div><i>03</i><span><b>Weekly body check-in</b><small>Repeated measurements create meaningful trends.</small></span></div></div></div><div class="card signal hypothesis-card"><div class="signal-orb">✦</div><div><span class="eyebrow">What Arc will test</span><h3>Does this plan actually fit your life?</h3><p>Arc will watch completion, body changes, nutrition logs and movement. It will use “associated with” language until repeated evidence supports a stronger Signal.</p></div></div><div class="learning-stages"><div><b>WEEK 1</b><span>Baseline</span><small>Collect context</small></div><div><b>WEEKS 2–4</b><span>Patterns</span><small>Compare behaviors</small></div><div><b>WEEK 4+</b><span>Signals</span><small>Earn confidence</small></div></div><button class="btn start-arc-cta" data-start>Start My Arc →</button></div></div></div>`)
};

function evidenceStrip(){const d=statusData();return `<div class="evidence-strip">${Object.entries(d.streams).map(([k,v])=>`<div class="${v?'on':''}"><i>${v?'✓':'○'}</i><span>${k}</span></div>`).join('')}</div>`}

today=function(){
  const p=S.profile,l=S.logs,q=plan(),completed=S.history.workouts.length,next=q.split[Math.min(completed,q.split.length-1)]||q.split[0],d=statusData(),nut=sumNutrition();
  shell(`<div class="arc-brandbar"><div class="arc-wordmark"><span class="arc-mini-mark"></span><b>ARC</b><small>PROGRESS HAS A SHAPE</small></div><div class="profile-pill"><div><b>${esc(p.name||'Kimberly')}</b><span>TODAY</span></div><div class="avatar"></div></div></div><div class="today-hero"><span class="eyebrow">What matters today</span><h1>${esc(next)}</h1><p class="muted">${p.duration||30} minutes. One repeatable action gives Arc better evidence than a perfect day.</p></div><div class="today-layout"><div><div class="next-workout-card focus-now"><span class="eyebrow">Your focus</span><h2>${esc(next)}</h2><p>${p.duration||30} min · ${esc(p.location||'Your setup')}</p><button class="btn" data-go="train">Open today’s workout →</button></div><div class="card signal"><span class="eyebrow">✦ What Arc is watching</span><h3>${esc(initialHypothesis())}</h3><p class="tiny muted">Status: ${d.label}. Arc has evidence in ${d.active} of 4 data streams.</p>${evidenceStrip()}</div><div class="action-stack">${!String(p.nutrition||'').startsWith('Not')?`<div class="card action-card"><div class="action-icon">◒</div><div class="action-copy"><span>NUTRITION</span><b>${nut.cal?nut.cal.toLocaleString()+' kcal today':'No meals logged yet'}</b><small>${nut.protein||0}g protein · individual entries saved</small></div><button class="round-action" data-go="nutrition">＋</button></div>`:''}<div class="card action-card"><div class="action-icon">⌁</div><div class="action-copy"><span>ACTIVITY</span><b>${l.steps?l.steps.toLocaleString()+' steps':'Add today’s movement'}</b><small>Movement adds recovery context.</small></div><button class="round-action secondary-round" data-steps>＋</button></div></div></div><div><div class="section-head"><div><span class="eyebrow">Your Arc</span><h3>${d.label}</h3></div><button class="text-action" data-go="arc">View story →</button></div>${evidenceStrip()}<div class="mini-metrics"><div><span>WORKOUTS</span><b>${S.history.workouts.length}</b><small>saved</small></div><div><span>CHECK-INS</span><b>${S.history.body.length}</b><small>dated</small></div><div><span>MEALS</span><b>${todayNutrition().length}</b><small>today</small></div><div><span>STEPS</span><b>${l.steps?l.steps.toLocaleString():'—'}</b><small>today</small></div></div><div class="card quiet-card"><span class="eyebrow">Your Why</span><h3>${p.why?`“${esc(p.why)}”`:'Build a body you understand—not one you have to guess about.'}</h3></div></div></div>`, 'today');
};

train=function(){
  const p=S.profile,q=plan(),completed=S.history.workouts.length,nextIndex=Math.min(completed,q.split.length-1),next=q.split[nextIndex]||q.split[0],ex=exerciseSet(next);
  shell(`<div class="arc-brandbar"><div class="arc-wordmark"><span class="arc-mini-mark"></span><b>ARC</b><small>PROGRESS HAS A SHAPE</small></div><div class="profile-pill"><div><b>${esc(p.name||'Kimberly')}</b><span>TRAIN WITH INTENT</span></div><div class="avatar"></div></div></div><div class="train-head"><span class="eyebrow">Train</span><h1>Your plan should fit your life.</h1><p class="muted">Built from ${p.days} days, ${p.duration}-minute sessions, ${esc((p.activities||[]).join(', ')||'your preferences')} and ${esc(q.equipment)}.</p></div><div class="train-layout"><div><div class="section-head"><div><span class="eyebrow">Your schedule</span><h3>Planned sessions</h3></div></div><div class="session-list">${q.split.map((x,i)=>`<div class="session-row ${i<completed?'done':i===completed?'next':''}"><div class="session-status">${i<completed?'✓':i===completed?'▶':i+1}</div><div><b>${esc(x)}</b><span>${i<completed?'Completed':i===completed?'Up next':'Planned'} · ${p.duration} min</span></div></div>`).join('')}</div></div><div><div class="next-workout-card"><span class="eyebrow">Next up</span><h2>${esc(next)}</h2><p>${p.duration} minutes · ${esc(p.experience)}</p><div class="workout-meta"><span>${ex.length} exercises</span><span>${esc(q.equipment)}</span><span>Built from your inputs</span></div><button class="btn" data-workout>Start Workout →</button></div><div class="exercise-preview-grid">${ex.slice(0,3).map(x=>`<div class="exercise-preview"><div class="exercise-figure"></div><b>${esc(x)}</b><span>3 sets</span></div>`).join('')}</div></div></div>`, 'train');
};

workout=function(){
  const q=plan(),completed=S.history.workouts.length,name=q.split[Math.min(completed,q.split.length-1)]||q.split[0],exercises=exerciseSet(name);
  if(!S.activeWorkout||S.activeWorkout.name!==name)S.activeWorkout={name,index:0,sets:{},started:new Date().toISOString()};
  const i=Math.min(S.activeWorkout.index||0,exercises.length-1),ex=exercises[i];
  shell(`<div class="workout-top"><button class="back-chip" data-go="train">←</button><div><span class="eyebrow">Workout in progress</span><h2>${esc(name)}</h2></div><span class="workout-time">${i+1} / ${exercises.length}</span></div><div class="workout-progress"><i style="width:${((i+1)/exercises.length)*100}%"></i></div><div class="active-exercise-hero"><div class="active-figure"><div class="exercise-person"></div></div><div class="active-copy"><span class="eyebrow">Exercise ${i+1} of ${exercises.length}</span><h1>${esc(ex)}</h1><p class="muted">3 sets · controlled reps · rest as needed</p><div class="cue-chips"><span>Control</span><span>Comfortable range</span><span>Good form</span></div></div></div><div class="set-card"><div class="set-head"><b>Set</b><b>Weight</b><b>Reps</b><b>Done</b></div>${[1,2,3].map(n=>`<div class="set-line"><span>${n}</span><input class="workout-weight" inputmode="decimal" placeholder="lb"><input class="workout-reps" inputmode="numeric" value="10"><button class="set-check" type="button">○</button></div>`).join('')}</div><div class="workout-actions">${i<exercises.length-1?`<button class="btn" data-next-exercise>Save & Next Exercise →</button>`:`<button class="btn" data-complete-workout>Complete Workout →</button>`}<button class="btn secondary" data-go="train">Exit workout</button></div>`, null);
};

nutrition=function(){
  const p=S.profile,t=syncNutrition(),entries=todayNutrition();
  shell(`<div class="arc-brandbar"><div class="arc-wordmark"><span class="arc-mini-mark"></span><b>ARC</b><small>PROGRESS HAS A SHAPE</small></div><div class="profile-pill"><div><b>${esc(p.name||'Kimberly')}</b><span>FUEL WITH CONTEXT</span></div><div class="avatar"></div></div></div><div class="nutrition-head"><span class="eyebrow">Nutrition</span><h1>Fuel the pattern, not perfection.</h1><p class="muted">No personalized calorie or protein target has been assumed. Arc is recording what you choose to log.</p></div><div class="nutrition-layout"><div><div class="fuel-summary simple-total"><div><span class="eyebrow">Today so far</span><h2>${t.cal.toLocaleString()} kcal</h2><p>${t.protein}g protein · ${entries.length} entr${entries.length===1?'y':'ies'}</p></div></div><div class="section-head"><div><span class="eyebrow">Quick add</span><h3>Log a meal</h3></div></div><div class="quick-log-card"><input id="food034" class="input" placeholder="What did you eat?"><div class="quick-log-grid"><label><span>Calories</span><input id="cals034" class="input" type="number" inputmode="numeric" placeholder="Optional"></label><label><span>Protein</span><input id="prot034" class="input" type="number" inputmode="numeric" placeholder="Optional g"></label></div><button class="btn" data-addmeal>Save meal →</button></div><div class="section-head"><div><span class="eyebrow">Today’s entries</span><h3>Food history</h3></div></div><div class="meal-list">${entries.length?entries.slice().reverse().map(x=>`<div class="meal-entry"><div><b>${esc(x.food||'Meal')}</b><span>${x.time||''}</span></div><p>${(+x.calories||0)?(+x.calories).toLocaleString()+' kcal':''}${x.calories&&x.protein?' · ':''}${x.protein?x.protein+'g protein':''}</p></div>`).join(''):`<div class="empty-state">Your meals will appear here as you log them.</div>`}</div></div><div><div class="card signal nutrition-signal"><span class="eyebrow">✦ Nutrition Intelligence</span><h2>Arc needs repeated days, not one perfect day.</h2><p class="tiny muted">With enough history, Arc can compare your nutrition patterns with training completion, body changes and recovery context.</p><div class="confidence-row"><span>Signal status</span><b>${entries.length?'Watching':'Learning'}</b></div></div><div class="card quiet-card"><span class="eyebrow">Your tracking mode</span><h3>${esc(String(p.nutrition||'Guided').split(' — ')[0])}</h3><p class="tiny muted">You can add more detail later if it improves the usefulness of your data.</p></div></div></div>`, 'today');
};

body=function(){
  const p=S.profile,h=S.history.body,last=h[h.length-1]||{},prev=h[h.length-2]||{}; const val=(k)=>last[k]||p[k]||'—'; const delta=(k)=>last[k]&&prev[k]?(+last[k]-+prev[k]).toFixed(1):null;
  shell(`<div class="top"><div><span class="eyebrow">Body</span><h2>Your Body</h2></div><div class="avatar"></div></div><p class="muted">A dated visual record of how your body is changing over time.</p><div class="body-layout"><div><div class="body-hero body-hero034"><svg class="body-figure" viewBox="0 0 260 430" role="img" aria-label="Body progress silhouette"><ellipse class="hair" cx="130" cy="47" rx="29" ry="34"/><circle class="skin" cx="130" cy="55" r="23"/><path class="skin" d="M109 80 C91 92 88 116 86 145 C83 176 75 202 67 228 C61 246 70 252 79 238 C88 220 97 198 101 176 L101 284 C98 316 96 348 98 392 C99 410 112 412 116 393 L126 293 L134 293 L144 393 C148 412 161 410 162 392 C164 348 162 316 159 284 L159 176 C163 198 172 220 181 238 C190 252 199 246 193 228 C185 202 177 176 174 145 C172 116 169 92 151 80 Z"/><path class="wear" d="M106 82 C115 90 145 90 154 82 L164 151 C154 163 106 163 96 151 Z"/><path class="wear" d="M98 151 C111 160 149 160 162 151 L165 232 C153 245 107 245 95 232 Z"/></svg><div class="body-callout weight">Weight · ${val('weight')}${val('weight')==='—'?'':' lb'}</div><div class="body-callout waist">Waist · ${val('waist')}${val('waist')==='—'?'':' in'}</div><div class="body-callout hips">${h.length} dated check-in${h.length===1?'':'s'}</div></div><div class="body-caption">Your visual is a progress reference—not a judgment or diagnosis.</div><div class="card signal"><span class="eyebrow">✦ Body Intelligence</span><h3>The trend is the story.</h3><p class="tiny muted">Arc compares repeated body check-ins with training, nutrition and activity. One measurement never gets to define your progress.</p></div></div><div><div class="body-section-title"><h3>New check-in</h3><small>All fields optional</small></div><div class="body-form-grid">${[['body-weight','Weight','lb'],['body-waist','Waist','in'],['body-hips','Hips','in'],['body-chest','Chest','in'],['body-thigh','Thigh','in'],['body-arm','Arm','in']].map(x=>`<label><span>${x[1]}</span><div><input id="${x[0]}" class="input" type="number" step="0.1" placeholder="—"><b>${x[2]}</b></div></label>`).join('')}</div><button class="btn" data-save-body>Save Check-In →</button><div class="body-section-title"><h3>Latest measurements</h3><small>${last.date||'No check-in yet'}</small></div><div class="measure-grid">${['weight','waist','hips','chest','thigh','arm'].map(k=>`<div class="measure-tile"><span>${k[0].toUpperCase()+k.slice(1)}</span><b>${val(k)}${val(k)==='—'?'':k==='weight'?' lb':' in'}</b>${delta(k)!==null?`<small class="delta">${+delta(k)>0?'+':''}${delta(k)} since prior</small>`:''}</div>`).join('')}</div><div class="checkin-history">${h.slice(-4).reverse().map(x=>`<div><b>${x.date}</b><span>${x.weight?x.weight+' lb':''}${x.waist?' · waist '+x.waist+' in':''}</span></div>`).join('')}</div></div></div>`, 'body');
};

arc=function(){
  const p=S.profile,d=statusData(),bw=S.history.body,wo=S.history.workouts,nu=S.history.nutrition; let insight='There isn’t enough repeated evidence for a strong Signal yet.'; let conf='Learning';
  if(wo.length>=3&&bw.length>=2){insight=`Your ${p.days}-day schedule appears to be becoming repeatable.`;conf='Early';}
  shell(`<div class="arc-brandbar"><div class="arc-wordmark"><span class="arc-mini-mark"></span><b>ARC</b><small>PROGRESS HAS A SHAPE</small></div><div class="profile-pill"><div><b>${esc(p.name||'Kimberly')}</b><span>YOUR STORY</span></div><div class="avatar"></div></div></div><div class="arc-page-head"><span class="eyebrow">Your Arc</span><h1>${d.label}.</h1><p class="muted">Not a scoreboard. A living explanation of what your body appears to be responding to.</p></div><div class="arc-story-layout"><div><div class="card"><span class="eyebrow">Evidence status</span><h3>${d.active} of 4 data streams active</h3>${evidenceStrip()}<p class="tiny muted">Arc avoids fake percentages. Evidence becomes more useful through repetition over time.</p></div><div class="section-head"><div><span class="eyebrow">Key moments</span><h3>Your timeline</h3></div></div><div class="story-timeline"><div class="story-event"><i></i><div><b>Baseline created</b><p>${esc(initialHypothesis())}</p></div></div>${wo.slice(-3).map(x=>`<div class="story-event"><i></i><div><b>${esc(x.name)} completed</b><p>${x.date} · ${x.exercises.length} exercises saved</p></div></div>`).join('')}${bw.slice(-3).map(x=>`<div class="story-event"><i></i><div><b>Body check-in</b><p>${x.date}${x.weight?' · '+x.weight+' lb':''}${x.waist?' · waist '+x.waist+' in':''}</p></div></div>`).join('')}</div></div><div><div class="card signal insight-feature"><span class="eyebrow">✦ What Arc knows so far</span><h2>${esc(insight)}</h2><p class="muted">${conf==='Early'?'This is an association, not proof of cause. Keep logging before Arc treats it as stable.':'That restraint is intentional. Arc should earn confidence before telling you what a pattern means.'}</p><div class="confidence-row"><span>Confidence</span><b>${conf}</b></div></div><div class="card"><span class="eyebrow">Evidence map</span><div class="evidence-list"><div><span>Training</span><b>${wo.length} workouts</b></div><div><span>Body</span><b>${bw.length} check-ins</b></div><div><span>Nutrition</span><b>${nu.length} entries</b></div><div><span>Activity</span><b>${S.logs.steps?'Present':'Waiting'}</b></div></div></div><div class="card quiet-card"><span class="eyebrow">Next unlock</span><h3>${bw.length<2?'Add another body check-in.':wo.length<3?'Complete another planned workout.':'Keep repeating the pattern.'}</h3></div></div></div>`, 'arc');
};

document.addEventListener('click',e=>{
  if(e.target.closest('[data-next-exercise]')){e.preventDefault();e.stopImmediatePropagation();S.activeWorkout.index=(S.activeWorkout.index||0)+1;save();workout();return}
  if(e.target.closest('[data-complete-workout]')){e.preventDefault();e.stopImmediatePropagation();const q=plan(),name=S.activeWorkout?.name||q.split[0],ex=exerciseSet(name);S.history.workouts.push({date:dayKey(),time:new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),name,exercises:ex});S.logs.workouts=S.history.workouts.length;delete S.activeWorkout;S.screen='train';save();render();return}
  if(e.target.closest('[data-addmeal]')){e.preventDefault();e.stopImmediatePropagation();const food=$('#food034')?.value.trim();const calories=Number($('#cals034')?.value||0),protein=Number($('#prot034')?.value||0);if(!food&&!calories&&!protein)return;S.history.nutrition.push({date:dayKey(),time:new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),food:food||'Meal',calories,protein});syncNutrition();nutrition();return}
  if(e.target.closest('[data-save-body]')){e.preventDefault();e.stopImmediatePropagation();const g=id=>$('#'+id)?.value||'';const x={date:dayKey(),weight:g('body-weight'),waist:g('body-waist'),hips:g('body-hips'),chest:g('body-chest'),thigh:g('body-thigh'),arm:g('body-arm')};if(!Object.values(x).some((v,i)=>i>0&&v))return;S.history.body.push(x);['weight','waist','hips','chest','thigh','arm'].forEach(k=>{if(x[k])S.profile[k]=x[k]});S.logs.bodyChecks=S.history.body.length;save();body();return}
},true);

if(typeof S!=='undefined')render();