// Arc POC 0.5 — Signals + longitudinal Arc + richer Body, Workout, Nutrition.
(function(){
  if(typeof S==='undefined') return;
  const H=()=>S.history||{workouts:[],nutrition:[],body:[],activity:[],sleep:[],signals:[]};
  const day=()=>new Date().toISOString().slice(0,10);
  const latest=(arr)=>arr&&arr.length?arr.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).at(-1):null;
  const first=(arr)=>arr&&arr.length?arr.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)))[0]:null;
  const fmt=(d)=>{try{return new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:new Date(d).getFullYear()!==new Date().getFullYear()?'numeric':undefined})}catch(e){return d||''}};
  const num=v=>v===''||v==null?null:+v;
  const signals=()=>{try{return ArcData?.evaluateSignals?.()||H().signals||[]}catch(e){return H().signals||[]}};
  const evidence=()=>{try{return ArcData?.evidenceStatus?.()||null}catch(e){return null}};
  const delta=(a,b)=>a!=null&&b!=null?+(+b-+a).toFixed(1):null;
  const esc2=s=>esc(s==null?'':String(s));
  const signalIcon=s=>s?.status==='active'?'✦':'◌';
  const signalTone=s=>s?.status==='active'?'active':'watching';

  function signalCard(s,compact=false){
    if(!s)return '';
    return `<button class="v05-signal-card ${signalTone(s)} ${compact?'compact':''}" data-signal-id="${esc2(s.id)}"><div class="v05-signal-top"><span>${signalIcon(s)}</span><div><small>${s.status==='active'?'EARNED SIGNAL':'ARC IS WATCHING'}</small><b>${esc2(s.title)}</b></div><i>›</i></div>${compact?'':`<p>${esc2(s.summary)}</p><div class="v05-signal-meta"><span>${esc2((s.domains||[]).join(' + ')||'Body Intelligence')}</span><span>${s.windowDays||'—'} days · ${esc2(s.confidence||'Learning')}</span></div>`}</button>`;
  }

  function contextualSignal(domain){
    const all=signals();
    return all.find(s=>(s.domains||[]).includes(domain)&&s.status==='active')||all.find(s=>(s.domains||[]).includes(domain))||all.find(s=>s.status==='active')||all[0];
  }

  today=function(){
    const p=S.profile||{},h=H(),q=plan(),e=evidence(),all=signals();
    const meals=h.nutrition.filter(x=>x.date===day()),body=latest(h.body),act=latest(h.activity.filter(x=>x.date===day()));
    const cal=meals.reduce((a,x)=>a+(+x.calories||0),0),protein=meals.reduce((a,x)=>a+(+x.protein||0),0),steps=act?.steps||S.logs?.steps||0;
    const done=h.workouts.length,next=q.split[Math.min(done,q.split.length-1)]||q.split[0]||'Full Body Strength';
    const lead=all.find(x=>x.status==='active')||all[0];
    shell(`<div class="dash-head"><div><span class="dash-date">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase()}</span><h1>Good morning, ${esc2(p.name||'Kimberly')}.</h1><p>Here’s what matters today.</p></div><div class="profile-medallion"></div></div>
      <section class="cinema-hero"><div class="cinema-copy"><span class="eyebrow">Today’s Focus</span><h2>${esc2(next)}</h2><p>${p.duration||30} min · built around your repeatable week</p><button class="btn hero-btn" data-go="train">Start Workout</button></div><div class="hero-message"><span>${lead?'WHAT ARC NOTICED':'WHY IT MATTERS'}</span><p>${lead?esc2(lead.summary):'Consistency creates the evidence Arc needs before it interprets change.'}</p>${lead?`<button class="v05-text-btn" data-signal-id="${esc2(lead.id)}">See the evidence →</button>`:''}</div></section>
      ${lead?`<section class="v05-today-signal"><div><span>${signalIcon(lead)}</span><small>${lead.status==='active'?'YOUR CURRENT SIGNAL':'ARC IS LEARNING'}</small><h3>${esc2(lead.title)}</h3></div><button data-signal-id="${esc2(lead.id)}">Explore Signal →</button></section>`:''}
      <div class="dash-tiles"><button data-go="nutrition"><i>⌑</i><b>Nutrition</b><span>${meals.length} meals</span><small>${cal||0} kcal · ${protein||0}g protein</small></button><button data-steps><i>⌁</i><b>Activity</b><span>${steps?steps.toLocaleString():'—'}</span><small>steps today</small></button><button data-go="body"><i>◯</i><b>Body</b><span>${body?'Last check-in':'No check-in yet'}</span><small>${body?fmt(body.date):'Add your baseline'}</small></button><button data-go="arc"><i>▥</i><b>Your Arc</b><span>${e?`${e.active} of ${e.total}`:'Building'}</span><small>evidence streams</small></button></div>
      <div class="dash-grid"><section class="editorial-card meals-card"><div class="card-title"><h3>Today’s Meals</h3><button data-go="nutrition">View All →</button></div>${meals.length?meals.slice(-3).map(x=>`<div class="editorial-row"><div class="meal-thumb"></div><div><b>${esc2(x.name||x.food||'Food entry')}</b><small>${x.protein||0}g protein</small></div><span>${x.calories||0} kcal</span></div>`).join(''):'<div class="empty-editorial">Nothing logged yet. One honest entry is more useful than a perfect day.</div>'}<button class="btn" data-go="nutrition">＋ Add a Meal</button></section><section class="editorial-card"><div class="card-title"><h3>Body Snapshot</h3><button data-go="body">View →</button></div>${body?['weight','waist','hips','chest'].filter(k=>body[k]!=null&&body[k]!=='').map(k=>`<div class="metric-row"><span>${k[0].toUpperCase()+k.slice(1)}</span><b>${body[k]} ${k==='weight'?'lb':'in'}</b></div>`).join(''):'<div class="empty-editorial">A dated body check-in unlocks real comparisons.</div>'}</section><section class="editorial-card insight-card"><div class="card-title"><h3>Body Intelligence</h3><button data-go="arc">Your Arc →</button></div>${lead?`<span class="insight-icon">${signalIcon(lead)}</span><h3>${esc2(lead.title)}</h3><p>${esc2(lead.summary)}</p><div class="insight-status"><span>${lead.status==='active'?'Signal earned':'Still watching'}</span><b>${esc2(lead.confidence||'Learning')}</b></div><button class="v05-text-btn" data-signal-id="${esc2(lead.id)}">Why Arc thinks this →</button>`:'<div class="empty-editorial">Arc is deliberately waiting for repeated evidence before making a claim.</div>'}</section></div>`, 'today');
  };

  arc=function(){
    const p=S.profile||{},h=H(),all=signals(),e=evidence(),b0=first(h.body),b1=latest(h.body),w0=num(b0?.weight),w1=num(b1?.weight),wa0=num(b0?.waist),wa1=num(b1?.waist);
    const events=[];
    if(b0)events.push({date:b0.date,type:'Baseline',title:'Your body entered the story',text:[b0.weight?`${b0.weight} lb`:null,b0.waist?`${b0.waist} in waist`:null].filter(Boolean).join(' · ')});
    h.workouts.forEach(x=>events.push({date:x.date,type:'Training',title:x.name||'Workout completed',text:`${x.durationMin||S.profile.duration||30} min${x.volume?` · ${Math.round(x.volume).toLocaleString()} volume`:''}`}));
    h.body.slice(1).forEach(x=>events.push({date:x.date,type:'Body',title:'Body check-in',text:[x.weight?`${x.weight} lb`:null,x.waist?`${x.waist} in waist`:null].filter(Boolean).join(' · ')}));
    all.filter(x=>x.status==='active').forEach(x=>events.push({date:String(x.evaluatedAt||day()).slice(0,10),type:'Signal',title:x.title,text:x.summary,signal:x.id}));
    events.sort((a,b)=>String(b.date).localeCompare(String(a.date)));
    shell(`<div class="arc-page-head v05-arc-hero"><span class="eyebrow">Your Arc</span><h1>Progress has a shape. Now you can see why.</h1><p>Actions, body changes and earned Signals live in one longitudinal story.</p><div class="v05-arc-summary"><div><span>TRAINING</span><b>${h.workouts.length}</b><small>sessions</small></div><div><span>BODY</span><b>${h.body.length}</b><small>check-ins</small></div><div><span>SIGNALS</span><b>${all.filter(x=>x.status==='active').length}</b><small>earned</small></div><div><span>CONTEXT</span><b>${e?`${e.active}/${e.total}`:'—'}</b><small>streams</small></div></div></div>
      <div class="v05-arc-layout"><div><section class="v05-progress-story"><div class="v05-story-head"><span class="eyebrow">Your story</span><h2>What changed — and what happened around it.</h2></div><div class="v05-story-stats">${wa0!=null&&wa1!=null?`<div><small>WAIST</small><b>${wa1} in</b><span class="${delta(wa0,wa1)<=0?'good':''}">${delta(wa0,wa1)>0?'+':''}${delta(wa0,wa1)} in since start</span></div>`:''}${w0!=null&&w1!=null?`<div><small>WEIGHT</small><b>${w1} lb</b><span>${delta(w0,w1)>0?'+':''}${delta(w0,w1)} lb since start</span></div>`:''}<div><small>CONSISTENCY</small><b>${h.workouts.length}</b><span>completed sessions</span></div></div>${events.length?`<div class="v05-timeline">${events.slice(0,14).map(x=>`<div class="v05-event ${x.type.toLowerCase()}"><i></i><div class="v05-event-date">${fmt(x.date)}</div><div><small>${esc2(x.type).toUpperCase()}</small><b>${esc2(x.title)}</b><p>${esc2(x.text)}</p>${x.signal?`<button class="v05-text-btn" data-signal-id="${esc2(x.signal)}">Open Signal →</button>`:''}</div></div>`).join('')}</div>`:'<div class="empty-editorial">Your timeline will build as you log real days.</div>'}</section></div><aside><section class="v05-section"><div class="v05-story-head"><span class="eyebrow">Signals</span><h2>What Arc has learned.</h2></div>${all.length?all.map(s=>signalCard(s)).join(''):'<div class="editorial-card empty-editorial">No Signal yet. Arc is waiting for enough repeated evidence.</div>'}</section><section class="editorial-card v05-evidence"><span class="eyebrow">Evidence Map</span><h3>What Arc can compare</h3>${Object.entries(e?.streams||{}).map(([k,v])=>`<div><span>${k}</span><b>${v||0}</b></div>`).join('')}<p>More data is not the goal. Enough comparable evidence is.</p></section></aside></div>`, 'arc');
  };

  body=function(){
    const h=H(),p=S.profile||{},b0=first(h.body),b1=latest(h.body),sig=contextualSignal('Body');
    const metrics=['weight','waist','hips','chest','thigh','arm'];
    const labels={weight:'Weight',waist:'Waist',hips:'Hips',chest:'Chest',thigh:'Thigh',arm:'Arm'};
    const unit=k=>k==='weight'?'lb':'in';
    const current=k=>num(b1?.[k])??num(p[k]);
    const start=k=>num(b0?.[k]);
    shell(`<div class="page-kicker v05-body-head"><span>BODY</span><h1>The trend is the story.</h1><p>Your measurements are context, not grades. Arc looks at how they change alongside what you do.</p></div>
      <section class="v05-body-grid"><div class="v05-body-visual"><div class="v05-body-photo"><div class="v05-body-overlay"><span class="eyebrow">Body Map</span><h2>${b1?'Latest check-in '+fmt(b1.date):'Build your baseline'}</h2>${metrics.slice(0,4).filter(k=>current(k)!=null).map((k,i)=>`<div class="v05-callout c${i+1}"><small>${labels[k]}</small><b>${current(k)} ${unit(k)}</b>${start(k)!=null&&delta(start(k),current(k))!==0?`<span>${delta(start(k),current(k))>0?'+':''}${delta(start(k),current(k))} ${unit(k)}</span>`:''}</div>`).join('')}</div></div><p class="tiny muted">A visual progress reference—not a diagnosis or a body-type prescription.</p>${sig?signalCard(sig,true):''}</div><div><section class="editorial-card"><div class="card-title"><h3>Measurements</h3><span class="tiny muted">${h.body.length} check-in${h.body.length===1?'':'s'}</span></div><div class="v05-measure-grid">${metrics.map(k=>`<div><small>${labels[k]}</small><b>${current(k)!=null?`${current(k)} ${unit(k)}`:'—'}</b>${start(k)!=null&&current(k)!=null?`<span class="${delta(start(k),current(k))<0?'good':''}">${delta(start(k),current(k))>0?'+':''}${delta(start(k),current(k))} ${unit(k)}</span>`:'<span>Waiting for comparison</span>'}</div>`).join('')}</div><button class="btn" data-measure>Update Measurements</button></section><section class="editorial-card v05-body-history"><div class="card-title"><h3>Check-in History</h3><span class="tiny muted">Recent</span></div>${h.body.length?h.body.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,6).map(x=>`<div class="v05-history-row"><span>${fmt(x.date)}</span><b>${x.weight?x.weight+' lb':'—'}</b><b>${x.waist?x.waist+' in waist':'—'}</b></div>`).join(''):'<div class="empty-editorial">Your first dated check-in starts the trend.</div>'}</section></div></section>`, 'body');
  };

  nutrition=function(){
    const h=H(),p=S.profile||{},todayMeals=h.nutrition.filter(x=>x.date===day()),sig=contextualSignal('Nutrition');
    const grouped={};h.nutrition.forEach(x=>(grouped[x.date]||(grouped[x.date]=[])).push(x));
    const days=Object.keys(grouped).sort().reverse().slice(0,7);
    const todayCal=todayMeals.reduce((a,x)=>a+(+x.calories||0),0),todayProtein=todayMeals.reduce((a,x)=>a+(+x.protein||0),0);
    shell(`<div class="nutrition-head"><span class="eyebrow">Nutrition</span><h1>Fuel the pattern, not perfection.</h1><p>Today is one data point. Arc cares more about what repeats.</p></div><div class="v05-nutrition-layout"><div><section class="editorial-card v05-fuel-today"><div class="v05-fuel-number"><small>TODAY</small><b>${todayCal.toLocaleString()}</b><span>kcal logged</span></div><div><small>PROTEIN</small><b>${todayProtein}g</b><span>${todayMeals.length} meal${todayMeals.length===1?'':'s'}</span></div></section><section class="editorial-card"><div class="card-title"><h3>Quick Add</h3><span class="tiny muted">Keep it easy</span></div><input id="food034" class="input" placeholder="What did you eat?"><div class="quick-log-grid"><label><span>Calories</span><input id="cals034" class="input" type="number" inputmode="numeric" placeholder="0"></label><label><span>Protein</span><input id="prot034" class="input" type="number" inputmode="numeric" placeholder="0 g"></label></div><button class="btn" data-addmeal>Add to Today →</button></section>${sig?signalCard(sig):''}</div><aside><section class="editorial-card"><div class="card-title"><h3>Recent Days</h3><span class="tiny muted">History</span></div>${days.length?days.map(d=>{const items=grouped[d],c=items.reduce((a,x)=>a+(+x.calories||0),0),pr=items.reduce((a,x)=>a+(+x.protein||0),0);return `<div class="v05-nutri-day"><div><b>${d===day()?'Today':fmt(d)}</b><small>${items.length} entr${items.length===1?'y':'ies'}</small></div><span>${c} kcal</span><span>${pr}g protein</span></div>`}).join(''):'<div class="empty-editorial">Your nutrition history will appear here as you log.</div>'}</section><section class="editorial-card quiet-card"><span class="eyebrow">Arc’s rule</span><h3>Useful beats perfect.</h3><p class="tiny muted">Arc uses repeated patterns and comparative days. It does not need flawless logging to become useful.</p></section></aside></div>`, 'nutrition');
  };

  workout=function(){
    const p=S.profile||{},q=plan();
    S.activeWorkout=S.activeWorkout||{name:q.split[Math.min(H().workouts.length,q.split.length-1)]||q.split[0]||'Full Body Strength',index:0,sets:{}};
    const name=S.activeWorkout.name,exercises=(typeof exerciseSet==='function'?exerciseSet(name):['Goblet Squat','Romanian Deadlift','Supported Row','Floor Press','Dead Bug']);
    const idx=Math.min(S.activeWorkout.index||0,exercises.length-1),ex=exercises[idx];
    S.activeWorkout.sets=S.activeWorkout.sets||{};S.activeWorkout.sets[ex]=S.activeWorkout.sets[ex]||[{weight:'',reps:10,done:false},{weight:'',reps:10,done:false},{weight:'',reps:10,done:false}];save();
    const sets=S.activeWorkout.sets[ex],prev=H().workouts.slice().reverse().find(w=>Array.isArray(w.exercises)&&w.exercises.includes(ex));
    shell(`<div class="workout-top"><button class="back-chip" data-go="train">←</button><div><span class="eyebrow">Workout in progress</span><h2>${esc2(name)}</h2></div><span class="workout-time">${idx+1} / ${exercises.length}</span></div><section class="active-exercise-hero v05-workout-hero"><div class="active-copy"><span class="eyebrow">Exercise ${idx+1} of ${exercises.length}</span><h1>${esc2(ex)}</h1><p>${prev?'You’ve done this movement before. Beat your previous effort only if today feels right.':'Own the movement first. Progress can come later.'}</p><div class="cue-chips"><span>Control the rep</span><span>Stay stable</span><span>Leave 1–2 in reserve</span></div></div></section><div class="v05-workout-layout"><div><section class="set-card"><div class="set-head"><b>Set</b><b>Weight</b><b>Reps</b><b>Done</b></div>${sets.map((s,i)=>`<div class="set-line"><span>${i+1}</span><input inputmode="decimal" data-v05-set-weight="${i}" placeholder="lb" value="${esc2(s.weight)}"><input inputmode="numeric" data-v05-set-reps="${i}" value="${esc2(s.reps)}"><button class="set-check ${s.done?'done':''}" data-v05-set-done="${i}">${s.done?'✓':'○'}</button></div>`).join('')}</section><div class="v05-workout-actions">${idx<exercises.length-1?`<button class="btn" data-v05-next-exercise>Next Exercise →</button>`:`<button class="btn" data-v05-finish-workout>Finish Workout →</button>`}</div></div><aside><section class="editorial-card"><span class="eyebrow">Form Guide</span><h3>Short cues. Full attention.</h3><p class="tiny muted">Arc keeps the active screen focused. Dedicated movement tutorials can sit one tap away without crowding the set log.</p></section><section class="editorial-card"><span class="eyebrow">Previous</span><h3>${prev?'History available':'First logged session'}</h3><p class="tiny muted">${prev?`Last completed ${fmt(prev.date)}.`:'Your completed sets today become the reference for next time.'}</p></section></aside></div>`, null);
  };

  function signalDetail(id){
    const s=signals().find(x=>x.id===id);if(!s)return arc();
    const e=s.evidence||{};
    shell(`<div class="v05-signal-detail"><button class="back-chip" data-v05-signal-back>← Your Arc</button><div class="v05-signal-hero ${signalTone(s)}"><span>${signalIcon(s)}</span><small>${s.status==='active'?'EARNED SIGNAL':'ARC IS WATCHING'}</small><h1>${esc2(s.title)}</h1><p>${esc2(s.summary)}</p><div class="v05-signal-badges"><b>${esc2(s.confidence||'Learning')} confidence</b><b>${s.windowDays||'—'} day window</b><b>${esc2((s.domains||[]).join(' + '))}</b></div></div><div class="v05-signal-detail-grid"><section class="editorial-card"><span class="eyebrow">Why Arc surfaced this</span><h2>The evidence behind the Signal.</h2><div class="v05-evidence-detail">${Object.entries(e).map(([k,v])=>`<div><span>${k.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}</span><b>${typeof v==='number'?v.toLocaleString():esc2(v)}</b></div>`).join('')||'<p class="tiny muted">Arc is still collecting enough comparable evidence to quantify this pattern.</p>'}</div></section><section class="editorial-card"><span class="eyebrow">What this means</span><h2>Useful context, not a command.</h2><p>Arc is describing an observed pattern in your own history. It is not claiming this pattern was caused by a single behavior.</p><div class="v05-signal-principle"><b>Trend over day.</b><span>Repeated evidence matters more than one measurement or one workout.</span></div><div class="v05-signal-principle"><b>Association over certainty.</b><span>Arc earns stronger language only as evidence improves.</span></div></section></div></div>`, 'arc');
  }

  document.addEventListener('click',e=>{
    const sig=e.target.closest('[data-signal-id]');if(sig){e.preventDefault();e.stopImmediatePropagation();S.activeSignalId=sig.dataset.signalId;save();signalDetail(S.activeSignalId);return}
    if(e.target.closest('[data-v05-signal-back]')){e.preventDefault();e.stopImmediatePropagation();S.activeSignalId=null;save();arc();return}
    const dw=e.target.closest('[data-v05-set-weight]');
    if(e.target.closest('[data-v05-set-done]')){e.preventDefault();e.stopImmediatePropagation();const b=e.target.closest('[data-v05-set-done]'),i=+b.dataset.v05SetDone,ex=(typeof exerciseSet==='function'?exerciseSet(S.activeWorkout.name):[])[S.activeWorkout.index||0];S.activeWorkout.sets[ex][i].done=!S.activeWorkout.sets[ex][i].done;save();workout();return}
    if(e.target.closest('[data-v05-next-exercise]')){e.preventDefault();e.stopImmediatePropagation();S.activeWorkout.index=(S.activeWorkout.index||0)+1;save();workout();return}
    if(e.target.closest('[data-v05-finish-workout]')){e.preventDefault();e.stopImmediatePropagation();const aw=S.activeWorkout,q=plan(),name=aw?.name||q.split[0],exs=typeof exerciseSet==='function'?exerciseSet(name):Object.keys(aw?.sets||{});let volume=0;Object.values(aw?.sets||{}).flat().forEach(s=>{if(s.done)volume+=(+s.weight||0)*(+s.reps||0)});H().workouts.push({date:day(),completedAt:new Date().toISOString(),name,durationMin:+S.profile.duration||30,completed:true,exercises:exs,sets:aw.sets,volume:volume||null});S.logs.workouts=H().workouts.length;delete S.activeWorkout;try{ArcData?.evaluateSignals?.()}catch(err){}S.screen='train';save();render();return}
  },true);
  document.addEventListener('input',e=>{
    const w=e.target.closest('[data-v05-set-weight]'),r=e.target.closest('[data-v05-set-reps]');if(!w&&!r)return;
    const index=+(w?w.dataset.v05SetWeight:r.dataset.v05SetReps),ex=(typeof exerciseSet==='function'?exerciseSet(S.activeWorkout.name):[])[S.activeWorkout.index||0];if(!ex)return;S.activeWorkout.sets[ex][index][w?'weight':'reps']=e.target.value;save();
  });

  if(['today','arc','body','nutrition','workout'].includes(S.screen)) render();
})();
