// ARC 80/20 signature runtime — event driven, no MutationObserver.
(function(){
if(typeof S==='undefined')return;
const oldToday=typeof today==='function'?today:null;let pending=null;
const key=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=n=>Math.round(+n||0).toLocaleString(),safe=v=>typeof esc==='function'?esc(v):String(v||'');
function day(){if(!S.nutritionV1)return null;S.nutritionV1.days=S.nutritionV1.days||{};const d=S.nutritionV1.days[key()]||(S.nutritionV1.days[key()]={meals:{},custom:[]});d.meals=d.meals||{};d.custom=Array.isArray(d.custom)?d.custom:[];d.custom.forEach(x=>x.balance=x.balance||'flex');S.nutritionV1.balanceDraft=S.nutritionV1.balanceDraft||'flex';return d}
function plan(){return window.ArcNutrition?.plan?.[new Date().getDay()]||null}
function totals(){const d=day(),p=plan(),target=Math.max(1,+S.nutritionV1?.targets?.calories||2000),foundationTarget=Math.round(target*.8),flexTarget=target-foundationTarget;let foundation=0,flex=0;const fi=[],xi=[];if(d&&p){p.meals.forEach(m=>{const r=d.meals[m.id]||{};if(!r.logged)return;const portion=+r.portion||1,cal=Math.round((r.swap?m.cal*.98:m.cal)*portion),name=r.swap?(m.swap||m.name):m.name;foundation+=cal;fi.push({name,cal})});d.custom.forEach(x=>{const cal=Math.max(0,+x.calories||0),item={name:x.name||'Food',cal};if(x.balance==='foundation'){foundation+=cal;fi.push(item)}else{flex+=cal;xi.push(item)}})}const total=foundation+flex;return{target,foundationTarget,flexTarget,foundation,flex,total,foundationRatio:total?foundation/total*100:0,flexRatio:total?flex/total*100:0,fi,xi}}
function copy(b){if(!b.total)return['YOUR DAY IS OPEN','Build the foundation. Keep room for life.','Start with the fundamentals that support your goal. Flex is part of the plan—not a reward for being perfect.'];if(!b.flex)return['FOUNDATION BUILDING','Your foundation is taking shape.','Flex is available when you want it. You never need to earn it or force it into the day.'];if(b.flex>b.flexTarget)return['A MORE FLEXIBLE DAY','Keep shaping the day from here.','No reset required. Return to the fundamentals when it makes sense and keep moving forward.'];if(b.foundationRatio>=80)return['BALANCED SO FAR','Strong foundation. Room for real life.','Your choices are reflecting ARC’s 80/20 philosophy without turning the day into a score.'];return['FLEX IN USE','There’s still room to shape the day.','80/20 is a direction for sustainable consistency, not a pass/fail target.']}
function visual(b){const fp=Math.min(80,b.foundation/b.foundationTarget*80||0),xp=Math.min(20,b.flex/b.flexTarget*20||0);return `<svg class="arc8020-svg" viewBox="0 0 340 250" role="img" aria-label="80/20 Arc"><path class="arc8020-track" pathLength="100" d="M42 205 A136 136 0 1 1 298 205"/><path class="arc8020-segment foundation" pathLength="100" stroke-dasharray="79.3 20.7" d="M42 205 A136 136 0 1 1 298 205"/><path class="arc8020-segment flex" pathLength="100" stroke-dasharray="19.3 80.7" stroke-dashoffset="-80.7" d="M42 205 A136 136 0 1 1 298 205"/>${fp?`<path class="arc8020-fill foundation" pathLength="100" stroke-dasharray="${fp} ${100-fp}" d="M42 205 A136 136 0 1 1 298 205"/>`:''}${xp?`<path class="arc8020-fill flex" pathLength="100" stroke-dasharray="${xp} ${100-xp}" stroke-dashoffset="-80" d="M42 205 A136 136 0 1 1 298 205"/>`:''}<circle class="arc8020-joint-halo" cx="287.7" cy="109.1" r="6"/><circle class="arc8020-joint" cx="287.7" cy="109.1" r="2.5"/></svg>`}
function markup(){const b=totals(),c=copy(b),ratio=b.total?`${Math.round(b.foundationRatio)} / ${Math.round(b.flexRatio)}`:'80 / 20';return `<section class="arc8020-card" data-arc8020-card tabindex="0" aria-label="ARC 80/20. Open definition and today’s balance."><div class="arc8020-premise"><span>THE ARC · 80/20</span><b>80/20 is the philosophy. The Arc is how you see it.</b></div><div class="arc8020-copy"><div><span class="eyebrow">TODAY’S SHAPE</span><h2>${safe(c[1])}</h2><p>${safe(c[2])}</p></div><button type="button" data-arc8020-details>What is 80/20?</button></div><div class="arc8020-visual">${visual(b)}<div class="arc8020-center"><small>${c[0]}</small><b>${ratio}</b><span>${b.total?`${fmt(b.total)} kcal logged`:'FOUNDATION / FLEX'}</span></div><span class="arc8020-end foundation">FOUNDATION</span><span class="arc8020-end flex">FLEX</span></div><div class="arc8020-definition"><b>Build a strong foundation. Leave room for real life.</b><p>Aim for roughly 80% from the fundamentals that support your goals and leave roughly 20% for flexibility. It’s a guide, not a grade.</p></div><div class="arc8020-stats"><div class="foundation"><i></i><span><small>FOUNDATION</small><b>${fmt(b.foundation)} <em>/ ~${fmt(b.foundationTarget)} kcal</em></b></span></div><div class="flex"><i></i><span><small>FLEX</small><b>${fmt(b.flex)} <em>/ ~${fmt(b.flexTarget)} kcal</em></b></span></div></div><footer><span>Your Arc shows the balance taking shape. It never asks for perfection.</span><b>View today’s balance →</b></footer></section>`}
function inject(){if(S.screen!=='today')return;const stage=document.querySelector('.arc-stage')||document.querySelector('.phone');if(!stage||stage.querySelector('.arc8020-card'))return;const t=document.createElement('template');t.innerHTML=markup();const card=t.content.firstElementChild,hero=stage.querySelector('.cinema-hero'),passive=stage.querySelector('.arc-passive-morning'),weekly=stage.querySelector('.v06-weekly-teaser');if(hero)hero.insertAdjacentElement('afterend',card);else if(passive)passive.insertAdjacentElement('beforebegin',card);else if(weekly)weekly.insertAdjacentElement('beforebegin',card);else stage.prepend(card)}
function decorateNutrition(){const root=document.querySelector('.arc-nutrition-today'),d=day();if(!root||!d)return;const quick=root.querySelector('.arc-quick-log'),add=quick?.querySelector('[data-arc-add-custom]');if(add&&!quick.querySelector('.arc8020-choice')){const el=document.createElement('div');el.className='arc8020-choice';el.innerHTML=`<div><span class="eyebrow">HOW DOES THIS FIT TODAY?</span><p>Foundation if it replaces a planned, goal-supportive meal. Flex if it’s intentional room for something extra.</p></div><div class="arc8020-choice-buttons"><button data-arc8020-draft="foundation" class="${S.nutritionV1.balanceDraft==='foundation'?'active':''}">Foundation</button><button data-arc8020-draft="flex" class="${S.nutritionV1.balanceDraft!=='foundation'?'active':''}">Flex</button></div>`;add.before(el)}root.querySelectorAll('.arc-custom-row').forEach((row,i)=>{if(!d.custom[i]||row.querySelector('[data-arc8020-toggle-custom]'))return;const x=d.custom[i],b=document.createElement('button');b.className=`arc8020-custom-chip ${x.balance}`;b.dataset.arc8020ToggleCustom=i;b.textContent=`${x.balance==='foundation'?'Foundation':'Flex'} · change`;row.querySelector('div')?.appendChild(b)})}
function close(){document.querySelector('.arc8020-overlay')?.remove();document.body.classList.remove('arc8020-modal-open')}
function rows(items,empty){return items.length?items.map(x=>`<div class="arc8020-detail-row"><span><b>${safe(x.name)}</b></span><strong>${fmt(x.cal)} kcal</strong></div>`).join(''):`<div class="arc8020-detail-empty">${empty}</div>`}
function details(){close();const b=totals(),ratio=b.total?`${Math.round(b.foundationRatio)} / ${Math.round(b.flexRatio)}`:'80 / 20',el=document.createElement('div');el.className='arc8020-overlay';el.innerHTML=`<div class="arc8020-backdrop" data-arc8020-close></div><section class="arc8020-sheet" role="dialog" aria-modal="true" aria-label="What 80/20 means"><header><div><span class="eyebrow">THE ARC · 80/20</span><h2>Build the foundation.<br>Keep room for life.</h2></div><button type="button" data-arc8020-close aria-label="Close">×</button></header><div class="arc8020-explainer"><span>WHAT 80/20 MEANS</span><p><b>80/20 is a guide, not a grade.</b> Aim for roughly 80% of your choices to come from fundamentals that support your goals, while leaving roughly 20% for flexibility and real life.</p><div><article><strong>80% · Foundation</strong><span>Planned, repeatable behaviors that support the direction you want to go.</span></article><article><strong>20% · Flex</strong><span>Intentional flexibility that makes the plan sustainable in actual life.</span></article></div><small>80/20 is not a quota. A 100/0 day is fine. A more flexible day never requires a reset.</small></div><div class="arc8020-balance-head"><span>TODAY’S SHAPE</span><b>${ratio}</b></div><div class="arc8020-detail-columns"><section><div class="arc8020-detail-title foundation"><i></i><span><small>FOUNDATION</small><b>${fmt(b.foundation)} / ~${fmt(b.foundationTarget)} kcal</b></span></div>${rows(b.fi,'No Foundation foods logged yet.')}</section><section><div class="arc8020-detail-title flex"><i></i><span><small>FLEX</small><b>${fmt(b.flex)} / ~${fmt(b.flexTarget)} kcal</b></span></div>${rows(b.xi,'No Flex foods logged yet.')}</section></div><div class="arc8020-philosophy"><b>80/20 is the philosophy. The Arc is how you see it.</b><p>Over time, ARC can apply the same idea beyond food—training, movement, sleep and recovery—to show the shape of sustainable progress.</p></div></section>`;document.body.appendChild(el);document.body.classList.add('arc8020-modal-open');requestAnimationFrame(()=>el.querySelector('[data-arc8020-close]')?.focus())}
if(oldToday){today=function(){oldToday();inject()}}
document.addEventListener('click',e=>{if(e.target.closest('[data-arc-add-custom]'))pending={n:day()?.custom?.length||0,b:S.nutritionV1?.balanceDraft||'flex'}},true);
document.addEventListener('click',e=>{const d=e.target.closest('[data-arc8020-draft]');if(d){S.nutritionV1.balanceDraft=d.dataset.arc8020Draft;save();decorateNutrition();return}if(e.target.closest('[data-arc-add-custom]')&&pending){const x=day();if(x&&x.custom.length>pending.n)x.custom.at(-1).balance=pending.b;pending=null;save();return}const t=e.target.closest('[data-arc8020-toggle-custom]');if(t){const x=day()?.custom?.[+t.dataset.arc8020ToggleCustom];if(x){x.balance=x.balance==='foundation'?'flex':'foundation';save();window.ArcNutrition?.render?.()}return}if(e.target.closest('[data-arc8020-details]')||e.target.closest('.arc8020-card')){details();return}if(e.target.closest('[data-arc8020-close]'))close()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();const c=e.target.closest?.('.arc8020-card');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();details()}});window.addEventListener('arc:rendered',()=>{inject();decorateNutrition()});day();save();window.Arc8020={breakdown:totals,renderToday:inject,version:'0.7.5-runtime-stable-qa1'};
})();