// ARC stable 80/20 Today runtime — event driven, no MutationObserver.
(function(){
if(typeof S==='undefined')return;
const oldToday=typeof today==='function'?today:null;let pending=null;
const key=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fmt=n=>Math.round(+n||0).toLocaleString(),safe=v=>typeof esc==='function'?esc(v):String(v||'');
function day(){if(!S.nutritionV1)return null;S.nutritionV1.days=S.nutritionV1.days||{};const d=S.nutritionV1.days[key()]||(S.nutritionV1.days[key()]={meals:{},custom:[]});d.meals=d.meals||{};d.custom=Array.isArray(d.custom)?d.custom:[];d.custom.forEach(x=>x.balance=x.balance||'flex');S.nutritionV1.balanceDraft=S.nutritionV1.balanceDraft||'flex';return d}
function plan(){return window.ArcNutrition?.plan?.[new Date().getDay()]||null}
function totals(){const d=day(),p=plan(),target=Math.max(1,+S.nutritionV1?.targets?.calories||2000),foundationTarget=Math.round(target*.8),flexTarget=target-foundationTarget;let foundation=0,flex=0;const fi=[],xi=[];if(d&&p){p.meals.forEach(m=>{const r=d.meals[m.id]||{};if(!r.logged)return;const portion=+r.portion||1,cal=Math.round((r.swap?m.cal*.98:m.cal)*portion),name=r.swap?(m.swap||m.name):m.name;foundation+=cal;fi.push({name,cal})});d.custom.forEach(x=>{const cal=Math.max(0,+x.calories||0),item={name:x.name||'Food',cal};if(x.balance==='foundation'){foundation+=cal;fi.push(item)}else{flex+=cal;xi.push(item)}})}const total=foundation+flex;return{target,foundationTarget,flexTarget,foundation,flex,total,foundationRatio:total?foundation/total*100:0,flexRatio:total?flex/total*100:0,fi,xi}}
function copy(b){if(!b.total)return['YOUR DAY IS OPEN','Start with your foundation.','Build most of today around foods that support your plan and leave some room for real life.'];if(!b.flex)return['FOUNDATION BUILDING','Your foundation is taking shape.','Flex is available when you want it—not something you need to use.'];if(b.flex>b.flexTarget)return['A MORE FLEXIBLE DAY','Focus on your foundation from here.','No reset required. Keep the next choice simple and supportive.'];if(b.foundationRatio>=80)return['BALANCED SO FAR','Strong foundation today.','You’re leaving room for flexibility without losing the shape of the day.'];return['FLEX IN USE','There’s still room to shape the day.','The 80/20 Arc is a guide, not a grade.']}
function markup(){const b=totals(),c=copy(b),ratio=b.total?`${Math.round(b.foundationRatio)} / ${Math.round(b.flexRatio)}`:'80 / 20',fp=Math.min(80,b.foundation/b.foundationTarget*80||0),xp=Math.min(20,b.flex/b.flexTarget*20||0);return `<section class="arc8020-card" data-arc8020-card tabindex="0"><div class="arc8020-copy"><div><span class="eyebrow">TODAY’S 80/20 ARC</span><h2>${safe(c[1])}</h2><p>${safe(c[2])}</p></div><button type="button" data-arc8020-details>How 80/20 works →</button></div><div class="arc8020-visual"><svg class="arc8020-svg" viewBox="0 0 320 255"><path class="arc8020-track" pathLength="100" d="M40 205 A128 128 0 1 1 280 205"/><path class="arc8020-guide foundation" pathLength="100" stroke-dasharray="79 21" d="M40 205 A128 128 0 1 1 280 205"/><path class="arc8020-guide flex" pathLength="100" stroke-dasharray="19 81" stroke-dashoffset="-81" d="M40 205 A128 128 0 1 1 280 205"/>${fp?`<path class="arc8020-fill foundation" pathLength="100" stroke-dasharray="${fp} ${100-fp}" d="M40 205 A128 128 0 1 1 280 205"/>`:''}${xp?`<path class="arc8020-fill flex" pathLength="100" stroke-dasharray="${xp} ${100-xp}" stroke-dashoffset="-80" d="M40 205 A128 128 0 1 1 280 205"/>`:''}</svg><div class="arc8020-center"><small>${c[0]}</small><b>${ratio}</b><span>${b.total?`${fmt(b.total)} kcal logged`:'guide'}</span></div></div><div class="arc8020-stats"><div class="foundation"><i></i><span><small>FOUNDATION</small><b>${fmt(b.foundation)} <em>/ ~${fmt(b.foundationTarget)} kcal</em></b></span></div><div class="flex"><i></i><span><small>FLEX</small><b>${fmt(b.flex)} <em>/ ~${fmt(b.flexTarget)} kcal</em></b></span></div></div><footer><span>80/20 is a guide to the shape of your day—not a grade on your behavior.</span><b>View balance →</b></footer></section>`}
function inject(){if(S.screen!=='today')return;const stage=document.querySelector('.arc-stage')||document.querySelector('.phone');if(!stage||stage.querySelector('.arc8020-card'))return;const t=document.createElement('template');t.innerHTML=markup();const card=t.content.firstElementChild,passive=stage.querySelector('.arc-passive-morning'),hero=stage.querySelector('.cinema-hero'),weekly=stage.querySelector('.v06-weekly-teaser');if(passive)passive.insertAdjacentElement('afterend',card);else if(hero)hero.insertAdjacentElement('afterend',card);else if(weekly)weekly.insertAdjacentElement('beforebegin',card);else stage.prepend(card)}
function decorateNutrition(){const root=document.querySelector('.arc-nutrition-today'),d=day();if(!root||!d)return;const quick=root.querySelector('.arc-quick-log'),add=quick?.querySelector('[data-arc-add-custom]');if(add&&!quick.querySelector('.arc8020-choice')){const el=document.createElement('div');el.className='arc8020-choice';el.innerHTML=`<div><span class="eyebrow">HOW DOES THIS FIT TODAY?</span><p>Foundation if it replaces a planned meal. Flex if it’s something extra.</p></div><div class="arc8020-choice-buttons"><button data-arc8020-draft="foundation" class="${S.nutritionV1.balanceDraft==='foundation'?'active':''}">Foundation</button><button data-arc8020-draft="flex" class="${S.nutritionV1.balanceDraft!=='foundation'?'active':''}">Flex</button></div>`;add.before(el)}root.querySelectorAll('.arc-custom-row').forEach((row,i)=>{if(!d.custom[i]||row.querySelector('[data-arc8020-toggle-custom]'))return;const x=d.custom[i],b=document.createElement('button');b.className=`arc8020-custom-chip ${x.balance}`;b.dataset.arc8020ToggleCustom=i;b.textContent=`${x.balance==='foundation'?'Foundation':'Flex'} · change`;row.querySelector('div')?.appendChild(b)})}
function close(){document.querySelector('.arc8020-overlay')?.remove();document.body.classList.remove('arc8020-modal-open')}
function details(){close();const b=totals(),row=x=>`<div class="arc8020-detail-row"><span><b>${safe(x.name)}</b></span><strong>${fmt(x.cal)} kcal</strong></div>`,el=document.createElement('div');el.className='arc8020-overlay';el.innerHTML=`<div class="arc8020-backdrop" data-arc8020-close></div><section class="arc8020-sheet"><header><div><span class="eyebrow">TODAY’S BALANCE</span><h2>${b.total?`${Math.round(b.foundationRatio)} / ${Math.round(b.flexRatio)}`:'80 / 20 guide'}</h2></div><button data-arc8020-close>×</button></header><div class="arc8020-detail-columns"><section><h3>Foundation · ${fmt(b.foundation)} kcal</h3>${b.fi.map(row).join('')||'<p>No Foundation foods logged yet.</p>'}</section><section><h3>Flex · ${fmt(b.flex)} kcal</h3>${b.xi.map(row).join('')||'<p>No Flex foods logged yet.</p>'}</section></div><div class="arc8020-philosophy"><b>Build a strong foundation. Leave room for real life.</b><p>A more flexible day never requires a reset.</p></div></section>`;document.body.appendChild(el);document.body.classList.add('arc8020-modal-open')}
if(oldToday){today=function(){oldToday();inject()}}
document.addEventListener('click',e=>{if(e.target.closest('[data-arc-add-custom]'))pending={n:day()?.custom?.length||0,b:S.nutritionV1?.balanceDraft||'flex'}},true);
document.addEventListener('click',e=>{const d=e.target.closest('[data-arc8020-draft]');if(d){S.nutritionV1.balanceDraft=d.dataset.arc8020Draft;save();decorateNutrition();return}if(e.target.closest('[data-arc-add-custom]')&&pending){const x=day();if(x&&x.custom.length>pending.n)x.custom.at(-1).balance=pending.b;pending=null;save();return}const t=e.target.closest('[data-arc8020-toggle-custom]');if(t){const x=day()?.custom?.[+t.dataset.arc8020ToggleCustom];if(x){x.balance=x.balance==='foundation'?'flex':'foundation';save();window.ArcNutrition?.render?.()}return}if(e.target.closest('[data-arc8020-details]')||e.target.closest('.arc8020-card')){details();return}if(e.target.closest('[data-arc8020-close]'))close()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('arc:rendered',()=>{inject();decorateNutrition()});day();save();window.Arc8020={breakdown:totals,renderToday:inject,version:'0.7.5-runtime-stable'};
})();