// ARC Focus UI — literal implementation of the approved Focus-first visual North Star.
// Presentation-only layer: preserves existing state, history, workout engine, auth and cloud sync.
(function(){
  if(typeof S==='undefined')return;
  window.__ARC_FOCUS_UI=true;
  const DAY=86400000;
  const safe=v=>typeof esc==='function'?esc(v):String(v??'');
  const fmt=n=>Math.round(Number(n)||0).toLocaleString();
  const num=v=>v===''||v==null||!Number.isFinite(+v)?null:+v;
  const localDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const H=()=>S.history||{};
  function ui(){S.focusUI=S.focusUI&&typeof S.focusUI==='object'?S.focusUI:{};return S.focusUI}
  function persist(){try{save()}catch(e){}try{window.ArcPersistence?.flush?.()}catch(e){}}
  function svgIcon(name){
    const paths={
      today:'<path d="M4 11.2 12 4l8 7.2v8.3a.5.5 0 0 1-.5.5h-5v-5.3h-5V20h-5a.5.5 0 0 1-.5-.5z"/><path d="M2.8 12.1 12 3.8l9.2 8.3"/>',
      nutrition:'<path d="M18.7 4.2C12.6 4.3 7.8 7.4 6.9 13c5.1.5 9.9-2.1 11.8-8.8Z"/><path d="M6.8 13.1c-1.7 1.6-2.7 3.8-3 6.6M7.2 12.7c2.6-.6 5.1-.3 7.5.9"/>',
      train:'<path d="M4 9v6M7 7v10M17 7v10M20 9v6M7 12h10"/>',
      body:'<circle cx="12" cy="5.2" r="2.5"/><path d="M9.2 9c.6-1 1.6-1.6 2.8-1.6s2.2.6 2.8 1.6l1.4 4.4-2.1.8-.8-2.4v8.4h-2.6v-5.1H9.9v5.1H7.3v-8.4l-.8 2.4-2.1-.8Z"/>',
      more:'<circle cx="5" cy="12" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="19" cy="12" r="1.6"/>',
      spark:'<path d="M4 15.8 8.2 11l3 2.6 4.2-6 4.6 3.1"/><circle cx="20" cy="10.7" r="1"/>',
      people:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.3"/><path d="M3.8 19c.5-4 2.6-6.1 5.2-6.1 2.7 0 4.8 2.1 5.2 6.1M14.2 14c2.9-.4 4.9 1.3 5.8 4.2"/>',
      gear:'<circle cx="12" cy="12" r="3"/><path d="m12 3 .7 2.1 2 .8 2-1 1.4 1.4-1 2 .8 2 2.1.7v2l-2.1.7-.8 2 1 2-1.4 1.4-2-1-2 .8L12 21h-2l-.7-2.1-2-.8-2 1L3.9 17.7l1-2-.8-2L2 13v-2l2.1-.7.8-2-1-2L5.3 4.9l2 1 2-.8L10 3Z"/>',
      question:'<circle cx="12" cy="12" r="9"/><path d="M9.7 9.2a2.6 2.6 0 0 1 5 1c0 2.1-2.7 2.4-2.7 4.1M12 17.4h.01"/>',
      link:'<path d="M9.6 14.4 8 16a3.5 3.5 0 1 1-5-5l3-3a3.5 3.5 0 0 1 5-.1M14.4 9.6 16 8a3.5 3.5 0 1 1 5 5l-3 3a3.5 3.5 0 0 1-5 .1M8.7 15.3l6.6-6.6"/>'
    };
    return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.more}</svg>`;
  }
  function nav(active){
    const rows=[['today','today','Today'],['nutrition','nutrition','Nutrition'],['train','train','Train'],['body','body','Body'],['community','more','More']];
    return `<nav class="focus-nav">${rows.map(([go,icon,label])=>`<button type="button" data-focus-go="${go}" class="${active===go?'active':''}">${svgIcon(icon)}<span>${label}</span></button>`).join('')}</nav>`;
  }
  function shellFocus(body,active){
    document.documentElement.classList.add('arc-focus-ui');
    shell(`<div class="focus-app">${body}${nav(active)}</div>`,null);
  }
  function dateLabel(){return new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
  function initials(){const n=(S.profile?.name||'A').trim();return safe(n.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'A')}
  function weekWorkouts(){
    const arr=Array.isArray(H().workouts)?H().workouts:[],now=new Date(),day=now.getDay(),delta=day===0?6:day-1,start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-delta).getTime();
    return arr.filter(x=>x?.completed!==false&&new Date(`${x.date||localDay()}T12:00:00`).getTime()>=start);
  }
  function workoutPlan(){try{return plan()}catch(e){return{split:['Full Body Strength']}}}
  function nextWorkout(){const q=workoutPlan(),target=Math.max(1,+S.profile?.days||3),count=Math.min(weekWorkouts().length,target),fallback=Math.min(+S.logs?.workouts||0,target),done=weekWorkouts().length?count:fallback;return {name:q.split?.[Math.min(done,Math.max(0,(q.split?.length||1)-1))]||q.split?.[0]||'Full Body Strength',done,target,remaining:Math.max(0,target-done)}}
  function lastMeasurement(){const all=[...(Array.isArray(H().measurements)?H().measurements:[]),...(Array.isArray(H().body)?H().body:[])].filter(Boolean).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return all.at(-1)||S.profile||{}}
  function firstMeasurement(){const all=[...(Array.isArray(H().measurements)?H().measurements:[]),...(Array.isArray(H().body)?H().body:[])].filter(Boolean).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return all[0]||S.profile||{}}
  function bodyDue(){const m=lastMeasurement();if(!m.date)return{due:true,label:'Start baseline'};const d=new Date(`${m.date}T12:00:00`),next=new Date(d.getTime()+7*DAY),now=new Date();return{due:now>=next,label:now>=next?'Due today':next.toLocaleDateString(undefined,{weekday:'long'})}}
  function nutritionPlan(){return window.ArcNutrition?.plan?.[new Date().getDay()]||{day:new Date().toLocaleDateString(undefined,{weekday:'long'}),meals:[{id:'breakfast',label:'BREAKFAST',name:'Protein-forward breakfast',detail:'Build a strong start',cal:400,protein:30},{id:'lunch',label:'LUNCH',name:'Mediterranean lunch',detail:'Protein + plants + whole grains',cal:520,protein:40},{id:'dinner',label:'DINNER',name:'Balanced dinner',detail:'Protein + vegetables + starch',cal:650,protein:45}]}}
  function nutritionDay(){S.nutritionV1=S.nutritionV1||{targets:{calories:2000,protein:145},days:{}};S.nutritionV1.targets=S.nutritionV1.targets||{calories:2000,protein:145};S.nutritionV1.days=S.nutritionV1.days||{};const k=localDay(),d=S.nutritionV1.days[k]||(S.nutritionV1.days[k]={meals:{},custom:[]});d.meals=d.meals||{};d.custom=Array.isArray(d.custom)?d.custom:[];return d}
  function nutritionTotals(){
    try{const b=window.Arc8020?.breakdown?.();if(b)return b}catch(e){}
    const p=nutritionPlan(),d=nutritionDay(),target=Math.max(1,+S.nutritionV1.targets?.calories||2000),foundationTarget=Math.round(target*.8),flexTarget=target-foundationTarget;let foundation=0,flex=0,totalProtein=0;
    p.meals.forEach(m=>{const r=d.meals[m.id]||{};if(!r.logged)return;const portion=+r.portion||1,cal=Math.round((r.swap?m.cal*.98:m.cal)*portion);foundation+=cal;totalProtein+=Math.round((r.swap?m.protein*.97:m.protein)*portion)});
    d.custom.forEach(x=>{const cal=Math.max(0,+x.calories||0);if(x.balance==='foundation')foundation+=cal;else flex+=cal;totalProtein+=Math.max(0,+x.protein||0)});
    const total=foundation+flex;return{target,foundationTarget,flexTarget,foundation,flex,total,foundationRatio:total?foundation/total*100:0,flexRatio:total?flex/total*100:0,protein:totalProtein};
  }
  function syncNutrition(){const d=nutritionDay(),p=nutritionPlan(),t=nutritionTotals();let protein=0;p.meals.forEach(m=>{const r=d.meals[m.id]||{};if(r.logged)protein+=Math.round((r.swap?m.protein*.97:m.protein)*(+r.portion||1))});d.custom.forEach(x=>protein+=Math.max(0,+x.protein||0));S.logs=S.logs||{};S.logs.cal=Math.round(t.total||0);S.logs.protein=Math.round(protein||0);persist()}
  function focusForToday(){
    const w=nextWorkout(),due=bodyDue(),b=nutritionTotals(),steps=+S.logs?.steps||0;
    if(w.remaining>0)return{kind:'train',kicker:"TODAY'S FOCUS",title:w.name,meta:[`${S.profile?.duration||30} min`,S.profile?.location||'Home or Gym'],cta:'Start workout',why:w.remaining===1?'You’re one session away from completing the training rhythm you’ve been able to sustain.':`You have ${w.remaining} planned sessions left this week. Today keeps the plan simple and repeatable.`};
    if(due.due)return{kind:'body',kicker:"TODAY'S FOCUS",title:'Body Check-in',meta:['~2 min','Measurements'],cta:'Check in',why:'Your last body snapshot is a week old. A repeatable check-in adds more context than another isolated number.'};
    if(!b.total)return{kind:'nutrition',kicker:"TODAY'S FOCUS",title:'Build Your Foundation',meta:['80/20','Nutrition'],cta:'Open nutrition',why:'Training is handled. The most useful next input is a normal day of eating—not a perfect one.'};
    if(steps<5000)return{kind:'today',kicker:"TODAY'S FOCUS",title:'Easy Movement',meta:['20 min','Low pressure'],cta:'Add movement',why:'Your planned work is covered. A little movement adds recovery context without turning today into another workout.'};
    return{kind:'arc',kicker:"TODAY'S FOCUS",title:'Keep the Day Balanced',meta:['80/20','Real life'],cta:'View your Arc',why:'You’ve handled the fundamentals. The best move now is to keep the rest of the day sustainable.'};
  }
  function focusHeroArt(kind){return `<div class="focus-hero-art ${kind}"><span></span><i></i><b></b></div>`}
  function todayFocus(){
    const p=S.profile||{},f=focusForToday(),b=nutritionTotals(),due=bodyDue(),nutLogged=b.total>0,nutPct=b.total?Math.round(b.foundationRatio):80,steps=+S.logs?.steps||0;
    shellFocus(`<section class="focus-page focus-today">
      <header class="focus-greeting"><div><span>${dateLabel()}</span><h1>Good morning,<br>${safe(p.name||'there')}.</h1></div><div class="focus-avatar">${initials()}</div></header>
      <article class="focus-primary-card"><div class="focus-primary-copy"><span>${f.kicker}</span><h2>${safe(f.title)}</h2><div class="focus-meta">${f.meta.map((x,i)=>`<b>${i?'⌂':'◷'} ${safe(x)}</b>`).join('')}</div><button type="button" data-focus-action="${f.kind}" aria-label="${safe(f.cta)}">→</button></div>${focusHeroArt(f.kind)}</article>
      <article class="focus-why"><div class="focus-bulb">✦</div><div><span>WHY ARC CHOSE THIS</span><p>${safe(f.why)}</p></div></article>
      <div class="focus-section-head"><div><span>AT A GLANCE</span></div><button type="button" data-focus-go="arc">See Details ›</button></div>
      <section class="focus-glance">
        <button class="mint" type="button" data-focus-go="nutrition">${svgIcon('nutrition')}<span>Nutrition</span><b>${nutLogged?'On track':'Plan ready'}</b><small>${nutPct}% Foundation</small></button>
        <button class="blue" type="button" data-focus-movement>${svgIcon('today')}<span>Movement</span><b>${steps?fmt(steps):'Add steps'}</b><small>${steps?'steps today':'Optional context'}</small></button>
        <button class="lavender" type="button" data-focus-go="body">${svgIcon('body')}<span>Body</span><b>Check-in</b><small>${safe(due.label)}</small></button>
      </section>
      <p class="focus-mantra">One focus. Real progress.</p>
    </section>`,'today');
  }
  function gauge(b){const has=b.total>0,fr=has?Math.max(0,Math.min(100,b.foundationRatio)):80,xr=has?Math.max(0,100-fr):20;return `<div class="focus-gauge" style="--foundation:${fr};--flex:${xr}"><svg viewBox="0 0 320 190" aria-label="80/20 balance arc"><path class="gauge-track" pathLength="100" d="M36 164 A124 124 0 0 1 284 164"/><path class="gauge-foundation" pathLength="100" stroke-dasharray="79 21" d="M36 164 A124 124 0 0 1 284 164"/><path class="gauge-flex" pathLength="100" stroke-dasharray="19 81" stroke-dashoffset="-81" d="M36 164 A124 124 0 0 1 284 164"/></svg><div class="focus-gauge-labels"><div><b>${has?Math.round(fr):80}%</b><span>Foundation</span><small>Habits that move<br>you forward</small></div><div><b>${has?Math.round(xr):20}%</b><span>Flex</span><small>Room for<br>real life</small></div></div></div>`}
  function arcFocus(){const b=nutritionTotals(),has=b.total>0,title=!has?'Your balance has room to take shape.':b.foundationRatio>=70&&b.foundationRatio<=92?'Your Balance Looks Strong':'Your Arc Is Still Taking Shape';shellFocus(`<section class="focus-page focus-arc"><div class="focus-arc-brand"><img src="assets/arc-monogram-transparent.svg" alt="ARC"><span>YOUR ARC</span></div><h1>${safe(title)}</h1><p class="focus-lead">${has?'You’re building the fundamentals while leaving room for what makes life enjoyable.':'80/20 gives the day structure without asking for perfection.'}</p>${gauge(b)}<button class="focus-info-btn" type="button" data-focus-8020>ⓘ &nbsp; What is 80/20? <span>›</span></button><blockquote>“Consistency creates progress.<br>Flexibility makes it last.”</blockquote><div class="focus-arc-summary"><span>Today</span><b>${has?`${fmt(b.foundation)} Foundation · ${fmt(b.flex)} Flex`:'Your guide is ready'}</b></div></section>`,'today')}
  function foodArt(){return `<svg class="focus-food-art" viewBox="0 0 360 150" aria-hidden="true"><defs><linearGradient id="plate" x1="0" x2="1"><stop stop-color="#dbe6d8"/><stop offset="1" stop-color="#eef0df"/></linearGradient></defs><ellipse cx="236" cy="73" rx="94" ry="54" fill="url(#plate)"/><ellipse cx="236" cy="73" rx="76" ry="40" fill="#f7f4ec"/><path d="M206 48c23-8 43 4 53 25-19 15-42 18-60 5 0-12 2-21 7-30Z" fill="#d77d51"/><path d="M188 66c-18-18-34-4-30 16 16 8 30 5 43-6" fill="#6f9a75"/><circle cx="278" cy="62" r="11" fill="#ba4e3d"/><circle cx="292" cy="82" r="8" fill="#d2a54e"/><path d="M250 92c21-18 41-3 48 14-22 10-40 5-52-6Z" fill="#799b63"/><circle cx="190" cy="100" r="9" fill="#e2d7b1"/><path d="M163 35c12 10 18 22 19 37" stroke="#365e47" stroke-width="4" fill="none" stroke-linecap="round"/></svg>`}
  function nutritionTabs(active){return `<div class="focus-tabs">${[['today','Today'],['plan','Plan'],['recipes','Recipes'],['log','Log']].map(([k,l])=>`<button type="button" data-focus-nut-tab="${k}" class="${active===k?'active':''}">${l}</button>`).join('')}</div>`}
  function mealRows(){const p=nutritionPlan(),d=nutritionDay();return p.meals.map(m=>{const logged=!!d.meals[m.id]?.logged;return `<button type="button" class="focus-meal-row" data-focus-meal="${safe(m.id)}"><span class="focus-meal-icon">${m.id==='breakfast'?'◌':m.id==='lunch'?'⌁':m.id==='dinner'?'◇':'·'}</span><span><b>${safe(m.label?.[0]+m.label?.slice(1).toLowerCase()||m.id)}</b><small>${safe(m.name)}</small></span><i class="${logged?'done':''}">${logged?'✓':''}</i></button>`}).join('')}
  function nutritionToday(){const b=nutritionTotals(),p=nutritionPlan(),d=nutritionDay(),logged=p.meals.filter(m=>d.meals[m.id]?.logged).length,fr=b.total?Math.round(b.foundationRatio):80,xr=b.total?Math.round(b.flexRatio):20;return `<section class="focus-nut-content"><article class="focus-nut-hero">${foodArt()}<div><h2>Eat for Your Goals.<br>Live for Real Life.</h2><p>Build the foundation. Keep the flexibility.</p></div></article><section class="focus-8020-bar"><span>YOUR 80/20 TODAY</span><div><i style="width:${fr}%"></i><em style="width:${xr}%"></em></div><div class="focus-8020-labels"><b>Foundation <small>${logged} of ${p.meals.length} planned</small></b><b>${b.total?`${fr}% / ${xr}%`:'80% / 20%'}</b></div></section><div class="focus-nut-actions"><button type="button" class="primary" data-focus-log-open>Log a Meal</button><button type="button" data-focus-view-plan>View Plan</button></div><h3 class="focus-list-title">TODAY'S MEALS</h3><div class="focus-meal-list">${mealRows()}</div></section>`}
  function nutritionPlanView(){const p=nutritionPlan(),d=nutritionDay();return `<section class="focus-plan-view"><div class="focus-copy-head"><span>${safe(String(p.day||'TODAY').toUpperCase())}</span><h2>Your Mediterranean plan.</h2><p>Simple meals built around protein, plants, whole grains and enough flexibility to make the plan livable.</p></div>${p.meals.map(m=>{const r=d.meals[m.id]||{};return `<article class="focus-plan-card ${r.logged?'done':''}"><div><span>${safe(m.label)}</span><h3>${safe(m.name)}</h3><p>${safe(m.detail||'')}</p></div><aside><b>${fmt(m.cal)} kcal</b><small>${fmt(m.protein)}g protein</small><button type="button" data-focus-meal="${safe(m.id)}">${r.logged?'✓ Logged':'Ate This'}</button></aside></article>`}).join('')}</section>`}
  function nutritionRecipes(){const p=nutritionPlan();return `<section class="focus-recipes"><div class="focus-copy-head"><span>RECIPES</span><h2>Meals that fit the foundation.</h2><p>Use the plan as a starting point, not a rulebook.</p></div><div class="focus-recipe-grid">${p.meals.map((m,i)=>`<article><div class="recipe-art r${i%4}"></div><span>${safe(m.label)}</span><h3>${safe(m.name)}</h3><p>${safe(m.detail||'')}</p></article>`).join('')}</div></section>`}
  function nutritionLog(){return `<section class="focus-log-view"><div class="focus-copy-head"><span>LOG</span><h2>Add what actually happened.</h2><p>Useful data beats perfect data.</p></div><div class="focus-log-card"><label>Meal or food<input id="focus-food-name" placeholder="What did you eat?"></label><div class="focus-log-grid"><label>Calories<input id="focus-food-cal" type="number" inputmode="numeric" placeholder="0"></label><label>Protein<input id="focus-food-protein" type="number" inputmode="numeric" placeholder="0 g"></label></div><span>HOW DOES THIS FIT TODAY?</span><div class="focus-balance-choice"><button type="button" data-focus-balance="foundation" class="active">Foundation</button><button type="button" data-focus-balance="flex">Flex</button></div><button type="button" class="focus-save-food" data-focus-save-food>Save to Today</button></div></section>`}
  function nutritionFocus(){const tab=ui().nutritionTab||'today';const content=tab==='plan'?nutritionPlanView():tab==='recipes'?nutritionRecipes():tab==='log'?nutritionLog():nutritionToday();shellFocus(`<section class="focus-page focus-nutrition"><header class="focus-page-header"><button type="button" data-focus-go="today">‹</button><h1>Nutrition</h1><span></span></header>${nutritionTabs(tab)}${content}</section>`,'nutrition')}
  function normalizeExercises(name){let list=[];try{list=exerciseSet(name)||[]}catch(e){}return list.map((x,i)=>typeof x==='string'?{name:x,sets:3,reps:i===2?12:10}:x).slice(0,5)}
  function trainTabs(active){return `<div class="focus-tabs three">${[['today','Today'],['programs','Programs'],['history','History']].map(([k,l])=>`<button type="button" data-focus-train-tab="${k}" class="${active===k?'active':''}">${l}</button>`).join('')}</div>`}
  function exerciseThumb(i){return `<span class="focus-ex-thumb e${i%5}"><i></i><b></b></span>`}
  function trainToday(){const w=nextWorkout(),ex=normalizeExercises(w.name),active=S.activeWorkout?.name===w.name?Math.max(0,+S.activeWorkout.index||0):0;return `<section class="focus-train-content"><article class="focus-train-hero"><div><span>UP NEXT</span><h2>${safe(w.name)}</h2><p>${S.profile?.duration||30} min · ${safe(S.profile?.location||'Home or Gym')}</p><button type="button" data-focus-start-workout>${S.activeWorkout?'Continue Workout →':'Start Workout →'}</button></div>${focusHeroArt('train')}</article><div class="focus-exercise-list">${ex.map((x,i)=>`<button type="button" data-focus-exercise="${i}">${exerciseThumb(i)}<span><b>${i+1}. ${safe(x.name)}</b><small>${x.sets||3} sets × ${x.reps||10} reps</small></span><i class="${i<active?'done':''}">${i<active?'✓':''}</i></button>`).join('')}</div></section>`}
  function trainPrograms(){const q=workoutPlan();return `<section class="focus-programs"><div class="focus-copy-head"><span>YOUR PROGRAM</span><h2>Built to be repeatable.</h2><p>${S.profile?.days||3} days · ${S.profile?.duration||30} minutes · ${safe(S.profile?.location||'Your setup')}</p></div>${(q.split||[]).map((x,i)=>`<article><span>DAY ${i+1}</span><h3>${safe(x)}</h3><p>${normalizeExercises(x).map(e=>safe(e.name)).join(' · ')}</p><button type="button" data-focus-program="${i}">Open workout ›</button></article>`).join('')}</section>`}
  function trainHistory(){const rows=(Array.isArray(H().workouts)?H().workouts:[]).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,12);return `<section class="focus-history"><div class="focus-copy-head"><span>HISTORY</span><h2>The work you’ve already done.</h2><p>Progress gets easier to trust when it has a record.</p></div>${rows.length?rows.map(x=>`<article><div><b>${safe(x.name||'Workout')}</b><small>${safe(x.date||'')}</small></div><span>${fmt(x.durationMin||S.profile?.duration||30)} min</span></article>`).join(''):'<div class="focus-empty">Your completed workouts will appear here.</div>'}</section>`}
  function trainFocus(){const tab=ui().trainTab||'today',content=tab==='programs'?trainPrograms():tab==='history'?trainHistory():trainToday();shellFocus(`<section class="focus-page focus-train"><header class="focus-page-header"><button type="button" data-focus-go="today">‹</button><h1>Train</h1><span></span></header>${trainTabs(tab)}${content}</section>`,'train')}
  const measureDefs=[['neck','Neck',17],['shoulders','Shoulders',23],['chest','Chest',34],['arm','Arms',41],['waist','Waist',50],['hips','Hips',59],['thigh','Thighs',72],['calf','Calves',88]];
  function bodyFigure(){return `<div class="focus-body-map"><svg viewBox="0 0 240 500" role="img" aria-label="Full body measurement map"><circle cx="120" cy="43" r="27"/><path d="M94 76c-14 8-21 25-22 46L61 215c-2 18 13 22 18 5l9-69 2 116c1 28-7 57-7 94l-2 105c0 20 17 22 21 3l17-151h2l17 151c4 19 21 17 21-3l-2-105c0-37-8-66-7-94l2-116 9 69c5 17 20 13 18-5l-11-93c-1-21-8-38-22-46-16 9-36 9-52 0Z"/></svg><div class="focus-body-lines">${measureDefs.map(([k,l,y],i)=>`<span class="${i%2?'right':'left'}" style="--y:${y}%"><b>${l}</b><i></i></span>`).join('')}</div></div>`}
  function measurementValue(m,k){const v=num(m[k]);return v==null?'—':`${v} in`}
  function bodyMeasurements(){const m=lastMeasurement();return `<section class="focus-body-measurements"><div class="focus-body-visual">${bodyFigure()}<div class="focus-body-values">${measureDefs.map(([k,l],i)=>`<span class="${i%2?'right':'left'}" data-k="${k}"><small>${l}</small><b>${measurementValue(m,k)}</b></span>`).join('')}</div></div><button type="button" class="focus-body-update" data-body-checkin-052>Update Measurements</button><p>Measure the same landmarks each time. Repeatability matters more than precision.</p></section>`}
  function bodyProgress(){const a=firstMeasurement(),b=lastMeasurement();return `<section class="focus-body-progress"><div class="focus-copy-head"><span>PROGRESS</span><h2>See the trend, not the noise.</h2><p>ARC compares repeated measurements with the behaviors around them.</p></div><div class="focus-body-progress-grid">${[['weight','Weight','lb'],['waist','Waist','in'],['hips','Hips','in'],['chest','Chest','in']].map(([k,l,u])=>{const x=num(a[k]),y=num(b[k]),d=x!=null&&y!=null?+(y-x).toFixed(1):null;return `<article><span>${l}</span><b>${y==null?'—':`${y} ${u}`}</b><small>${d==null?'Waiting for comparison':`${d>0?'+':''}${d} ${u} since start`}</small></article>`}).join('')}</div></section>`}
  function bodyPhotos(){return `<section class="focus-body-photos"><div class="focus-copy-head"><span>PHOTOS</span><h2>A visual record, when you want it.</h2><p>Progress photos are optional and private. ARC never needs them to give you useful guidance.</p></div><div class="focus-photo-placeholder"><div>＋</div><b>Add a private progress photo</b><small>Coming in the native iOS pilot</small></div></section>`}
  function bodyFocus(){const tab=ui().bodyTab||'measurements',content=tab==='progress'?bodyProgress():tab==='photos'?bodyPhotos():bodyMeasurements();shellFocus(`<section class="focus-page focus-body"><header class="focus-page-header"><button type="button" data-focus-go="today">‹</button><h1>Body</h1><span></span></header><div class="focus-tabs three">${[['measurements','Measurements'],['progress','Progress'],['photos','Photos']].map(([k,l])=>`<button type="button" data-focus-body-tab="${k}" class="${tab===k?'active':''}">${l}</button>`).join('')}</div>${content}</section>`,'body')}
  function moreFocus(){shellFocus(`<section class="focus-page focus-more"><header class="focus-page-header solo"><h1>More</h1></header><div class="focus-more-list"><button type="button" data-focus-go="arc"><i>${svgIcon('spark')}</i><span><b>Arc Insights</b><small>Your patterns. Our perspective.</small></span><em>›</em></button><button type="button" data-focus-community><i>${svgIcon('people')}</i><span><b>Community</b><small>Connect. Share. Stay inspired.</small></span><em>›</em></button><button type="button" data-connected-data><i>${svgIcon('link')}</i><span><b>Connected Data</b><small>Apple Health and future sources.</small></span><em>›</em></button><button type="button" data-focus-settings><i>${svgIcon('gear')}</i><span><b>Settings</b><small>Account, devices, preferences.</small></span><em>›</em></button><button type="button" data-focus-help><i>${svgIcon('question')}</i><span><b>Help & Support</b><small>We’re here when you need us.</small></span><em>›</em></button></div><article class="focus-more-promo"><div><span>ARC</span><h2>A stronger, healthier you<br>still fits a real life.</h2><p>That’s the arc.</p></div></article></section>`,'community')}
  function openOverlay(kind){
    document.querySelector('.focus-overlay')?.remove();
    let body='';
    if(kind==='8020')body=`<span class="focus-modal-kicker">THE 80/20 PRINCIPLE</span><h2>Build a strong foundation.<br>Leave room for real life.</h2><p><b>Foundation</b> is the roughly 80% of choices that consistently support your goals—planned meals, training, movement, sleep and recovery habits.</p><p><b>Flex</b> is the roughly 20% that makes the plan livable. Dessert, dinner out, a missed workout, a slower day. It belongs in the plan.</p><div class="focus-modal-note">80/20 is a guide, not a grade. The goal is a shape you can repeat.</div>`;
    if(kind==='community')body=`<span class="focus-modal-kicker">COMMUNITY</span><h2>Celebrate showing up.</h2><p>ARC community is designed around behavior, consistency and effort—not bodies or comparison.</p><div class="focus-community-mini"><div><b>Jen</b><span>completed a planned workout</span></div><div><b>Mike</b><span>hit a consistency milestone</span></div><div><b>Alex</b><span>showed up on a busy day</span></div></div>`;
    if(kind==='settings')body=`<span class="focus-modal-kicker">SETTINGS</span><h2>Your Arc, your data.</h2><p>Signed in as <b>${safe(window.ArcCloud?.user?.email||'your ARC account')}</b>.</p><div class="focus-settings-row"><span>Cloud sync</span><b>${window.ArcCloud?.ready?'Active':'Initializing'}</b></div><div class="focus-settings-row"><span>Local recovery snapshots</span><b>Protected</b></div><div class="focus-settings-row"><span>Nutrition philosophy</span><b>80/20</b></div>`;
    if(kind==='help')body=`<span class="focus-modal-kicker">HELP & SUPPORT</span><h2>ARC should make health feel simpler.</h2><p>If something feels confusing, broken or too busy, that’s product feedback—not something you should have to work around.</p><div class="focus-modal-note">Current build: Focus-first POC</div>`;
    const el=document.createElement('div');el.className='focus-overlay';el.innerHTML=`<div class="focus-overlay-backdrop" data-focus-close></div><section class="focus-modal"><button class="focus-modal-close" type="button" data-focus-close>×</button>${body}</section>`;document.body.appendChild(el);
  }
  function openFoodOverlay(){document.querySelector('.focus-overlay')?.remove();const el=document.createElement('div');el.className='focus-overlay';el.innerHTML=`<div class="focus-overlay-backdrop" data-focus-close></div><section class="focus-modal focus-food-modal"><button class="focus-modal-close" type="button" data-focus-close>×</button><span class="focus-modal-kicker">LOG A MEAL</span><h2>Add what actually happened.</h2><label>Meal or food<input id="focus-modal-food" placeholder="What did you eat?"></label><div class="focus-log-grid"><label>Calories<input id="focus-modal-cal" type="number" inputmode="numeric" placeholder="0"></label><label>Protein<input id="focus-modal-protein" type="number" inputmode="numeric" placeholder="0 g"></label></div><span class="focus-modal-kicker second">HOW DOES THIS FIT TODAY?</span><div class="focus-balance-choice modal"><button type="button" data-focus-modal-balance="foundation" class="active">Foundation</button><button type="button" data-focus-modal-balance="flex">Flex</button></div><button class="focus-save-food" type="button" data-focus-modal-save>Save to Today</button></section>`;document.body.appendChild(el)}

  // Replace signed-in presentation surfaces. Tool/workout/check-in screens remain on the proven engines beneath this layer.
  try{today=todayFocus;arc=arcFocus;nutrition=nutritionFocus;train=trainFocus;body=bodyFocus;community=moreFocus}catch(e){window.today=todayFocus;window.arc=arcFocus;window.nutrition=nutritionFocus;window.train=trainFocus;window.body=bodyFocus;window.community=moreFocus}

  document.addEventListener('click',e=>{
    const go=e.target.closest('[data-focus-go]');if(go){e.preventDefault();e.stopImmediatePropagation();S.screen=go.dataset.focusGo;persist();render();return}
    const action=e.target.closest('[data-focus-action]');if(action){e.preventDefault();e.stopImmediatePropagation();const k=action.dataset.focusAction;if(k==='train'||k==='nutrition'||k==='body'||k==='arc'){S.screen=k;persist();render();return}if(k==='today'){document.querySelector('[data-focus-movement]')?.click();return}}
    if(e.target.closest('[data-focus-movement]')){e.preventDefault();e.stopImmediatePropagation();const v=prompt('Steps today',S.logs?.steps||'');if(v!==null&&v!==''){S.logs=S.logs||{};S.logs.steps=Math.max(0,+v||0);persist();todayFocus()}return}
    const nt=e.target.closest('[data-focus-nut-tab]');if(nt){e.preventDefault();e.stopImmediatePropagation();ui().nutritionTab=nt.dataset.focusNutTab;persist();nutritionFocus();return}
    if(e.target.closest('[data-focus-view-plan]')){e.preventDefault();e.stopImmediatePropagation();ui().nutritionTab='plan';persist();nutritionFocus();return}
    const meal=e.target.closest('[data-focus-meal]');if(meal){e.preventDefault();e.stopImmediatePropagation();const d=nutritionDay(),id=meal.dataset.focusMeal,r=d.meals[id]||(d.meals[id]={portion:1,swap:false});r.logged=!r.logged;syncNutrition();nutritionFocus();return}
    if(e.target.closest('[data-focus-log-open]')){e.preventDefault();e.stopImmediatePropagation();openFoodOverlay();return}
    const bal=e.target.closest('[data-focus-balance]');if(bal){e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('[data-focus-balance]').forEach(x=>x.classList.toggle('active',x===bal));ui().logBalance=bal.dataset.focusBalance;persist();return}
    if(e.target.closest('[data-focus-save-food]')){e.preventDefault();e.stopImmediatePropagation();const name=document.querySelector('#focus-food-name')?.value.trim(),cal=+document.querySelector('#focus-food-cal')?.value||0,protein=+document.querySelector('#focus-food-protein')?.value||0;if(name||cal||protein){nutritionDay().custom.push({name:name||'Food',calories:cal,protein,balance:ui().logBalance||'foundation',loggedAt:new Date().toISOString()});syncNutrition();ui().nutritionTab='today';nutritionFocus()}return}
    const mt=e.target.closest('[data-focus-modal-balance]');if(mt){e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('[data-focus-modal-balance]').forEach(x=>x.classList.toggle('active',x===mt));ui().modalBalance=mt.dataset.focusModalBalance;persist();return}
    if(e.target.closest('[data-focus-modal-save]')){e.preventDefault();e.stopImmediatePropagation();const name=document.querySelector('#focus-modal-food')?.value.trim(),cal=+document.querySelector('#focus-modal-cal')?.value||0,protein=+document.querySelector('#focus-modal-protein')?.value||0;if(name||cal||protein){nutritionDay().custom.push({name:name||'Food',calories:cal,protein,balance:ui().modalBalance||'foundation',loggedAt:new Date().toISOString()});syncNutrition();document.querySelector('.focus-overlay')?.remove();nutritionFocus()}return}
    const tt=e.target.closest('[data-focus-train-tab]');if(tt){e.preventDefault();e.stopImmediatePropagation();ui().trainTab=tt.dataset.focusTrainTab;persist();trainFocus();return}
    if(e.target.closest('[data-focus-start-workout]')){e.preventDefault();e.stopImmediatePropagation();const w=nextWorkout();if(!S.activeWorkout||S.activeWorkout.name!==w.name)S.activeWorkout={name:w.name,index:0,sets:{}};S.screen='workout';persist();render();return}
    const ex=e.target.closest('[data-focus-exercise]');if(ex){e.preventDefault();e.stopImmediatePropagation();const w=nextWorkout();S.activeWorkout=S.activeWorkout&&S.activeWorkout.name===w.name?S.activeWorkout:{name:w.name,index:0,sets:{}};S.activeWorkout.index=+ex.dataset.focusExercise||0;S.screen='workout';persist();render();return}
    const prog=e.target.closest('[data-focus-program]');if(prog){e.preventDefault();e.stopImmediatePropagation();const q=workoutPlan(),name=q.split?.[+prog.dataset.focusProgram]||q.split?.[0]||'Workout';S.activeWorkout={name,index:0,sets:{}};S.screen='workout';persist();render();return}
    const bt=e.target.closest('[data-focus-body-tab]');if(bt){e.preventDefault();e.stopImmediatePropagation();ui().bodyTab=bt.dataset.focusBodyTab;persist();bodyFocus();return}
    if(e.target.closest('[data-focus-8020]')){e.preventDefault();e.stopImmediatePropagation();openOverlay('8020');return}
    if(e.target.closest('[data-focus-community]')){e.preventDefault();e.stopImmediatePropagation();openOverlay('community');return}
    if(e.target.closest('[data-focus-settings]')){e.preventDefault();e.stopImmediatePropagation();openOverlay('settings');return}
    if(e.target.closest('[data-focus-help]')){e.preventDefault();e.stopImmediatePropagation();openOverlay('help');return}
    if(e.target.closest('[data-focus-close]')){e.preventDefault();e.stopImmediatePropagation();document.querySelector('.focus-overlay')?.remove();return}
  },true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.focus-overlay')?.remove()});
  window.ArcFocusUI={version:'1.0',today:todayFocus,arc:arcFocus,nutrition:nutritionFocus,train:trainFocus,body:bodyFocus,more:moreFocus};
})();